### ISSUE TITLE
navigationItemRelated

### ISSUE THREAD

**Issue by luisjose-al** [VirtusLab-Open-Source/strapi-plugin-navigation#103]
Hey :) 
I'm trying to set up the navigation Item Related Model but when I do, this error shows up and I cannot get the Models fields then.
Idk if I'm doing it wrong? I will be very grateful for your help, Thanks :) 
<img width="808" alt="Captura de Pantalla 2021-11-08 a la(s) 16 31 54" src="https://user-images.githubusercontent.com/79721453/140829040-1fc98372-0dbd-4c68-a1fc-e886ee4bebdb.png">
<img width="756" alt="Captura de Pantalla 2021-11-08 a la(s) 16 30 44" src="https://user-images.githubusercontent.com/79721453/140829061-fbe8259a-99a6-47f0-83d7-ca51de036a15.png">

This is the error!
<img width="1089" alt="Captura de Pantalla 2021-11-08 a la(s) 16 31 19" src="https://user-images.githubusercontent.com/79721453/140829087-5ec99476-e146-45e2-9389-0e30172bfd90.png">

**Comment by sven-ra** [comment]
Exact same bug form me.

**Comment by ltsNotMike** [comment]
Closing issue due to merged fix. Please reopen if needed.
