### ISSUE TITLE
The polymorphic `name` and `Target` are required

### ISSUE THREAD

**Issue by anthonytison** [VirtusLab-Open-Source/strapi-plugin-navigation#105]
Plugin version : 1.1.0

Hi,

I'm trying to add the navigation system to a SingleType called `homepage`. 

After adding the `navigation` attribute inside the homepage.settings.json, i have the following error `The polymorphic "name" and "Target" are required` which appears when loading the form. If i remove it, it's back to normal.

Sample of the homepage.settings.json file : 
<pre>
{
  "kind": "singleType",
  "collectionName": "homepages",
  "info": {
    "name": "homepage",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
    },
    ...
 }
}
</pre>

What can i do wrong ? 

Thx

**Comment by jasonmarysael** [comment]
I'm having the same issue since the latest version. Had no issues with v1.0.4.

**Comment by racusrussia** [comment]
I join you. I have the same problem

**Comment by cyp3rius** [comment]
Thanks for reporting this, we are investigating this issue. By the first spot it is nit updated documentation.

Will keep you posted

**Comment by anthonytison** [comment]
Hi @cyp3rius, 
Did you find the solution to this problem or at least, do you have a lead ?

**Comment by graphicfox** [comment]
Hi @anthonytison the open pull request fixes the problems for me. Hope it gets soon merged

Merge pull request #108

**Comment by cyp3rius** [comment]
Fix from #108 has been released as `v1.1.1`, sorry for inconvenience and thanks for being patient :) 

Check the [release notes](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/releases/tag/v1.1.1)
