### ISSUE TITLE
No content types available

### ISSUE THREAD

**Issue by jasonmarysael** [VirtusLab-Open-Source/strapi-plugin-navigation#110]
Version: 1.1.1

For some reason I'm not able to select a content type option when creating a new navigation item.

![image](https://user-images.githubusercontent.com/28600053/142909774-5215a615-f60c-4d8d-abc0-e21e2cb478e4.png)

config/plugins.js:

![image](https://user-images.githubusercontent.com/28600053/142910003-e595b8e7-7eaa-456c-9b0f-8013f4776021.png)

api/page/models/page.settings.json:

![image](https://user-images.githubusercontent.com/28600053/142910245-c8578702-f504-49de-856d-ce35c3eaeb1c.png)

Could it be I've made a mistake with the 'relatedContentTypes' config (custom/plugins.js)? The documentation isn't very clear to me regarding that part.

**Comment by guizmo** [comment]
i am juste discovering strapi and i installed this plugin today
your settings look good to me (i'm NO expert)

<img width="712" alt="Screen Shot 2021-11-23 at 10 29 33" src="https://user-images.githubusercontent.com/699063/142950281-5ce4c439-b8d8-41fb-a6a4-843361e77fba.png">
<img width="677" alt="Screen Shot 2021-11-23 at 10 29 42" src="https://user-images.githubusercontent.com/699063/142950285-60c738ef-5b59-46d5-90ca-88575dd24bdb.png">
![Screen Shot 2021-11-23 at 10 30 44](https://user-images.githubusercontent.com/699063/142950289-f2711658-375f-489f-8d9d-75b63dc1ec9b.png)

**Comment by jasonmarysael** [comment]
Thx for verifying @guizmo. it seems I had to use 'application::page.page' instead of 'application::pages.pages' for some reason. Now it's working fine.
