### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading payload or uid)

### ISSUE THREAD

**Issue by anthonytison** [VirtusLab-Open-Source/strapi-plugin-navigation#113]
Hi,

When i save a menu, i always get the error `Cannot read properties of undefined (reading 'payload')`. This error seems to happen after the call because If i check the response (example below), i have the data with the list of my items.

Also if i refresh the navigation page, the error is `Cannot read properties of undefined (reading 'uid')` but the response (example below) shows the data.

FYI, i only set SingleTypes in the parameter `relatedContentTypes`.

Version : `1.1.1`

Configuration : 
<pre>
navigation: {
      additionalFields: [],
      allowedLevels: 2,
      contentTypesNameFields: {
        'homepage': ['title'],
      },
      relatedContentTypes: [
        'application:homepage.homepage'
      ]
}
</pre>

Response call `PUT http://localhost:1338/navigation/5` :
<pre>
{
  "id": 5,
  "name": "Top",
  "slug": "top",
  "visible": true,
  "items": [
    {
      "id": 15,
      "title": "Homepage",
      "type": "INTERNAL",
      "path": "/",
      "externalPath": null,
      "uiRouterKey": "homepage",
      "menuAttached": true,
      "order": 1,
      "parent": null,
      "master": {
        "id": 5,
        "name": "Top",
        "slug": "top",
        "visible": true,
        "created_by": 1,
        "updated_by": 1
      },
      "created_by": null,
      "updated_by": null,
      "created_at": "2021-11-24T14:40:38.174Z",
      "updated_at": "2021-11-24T14:40:38.180Z",
      "audience": [],
      "related": [
        { ... single type data }
      ]
    }
}
</pre>

**Comment by anthonytison** [comment]
hI @cyp3rius, did you make some progress on your investigation ?

**Comment by shanebeeston** [comment]
Im getting the same issue

**Comment by shanebeeston** [comment]
I got around this by deleting node_modules / .cache / .build folders and it worked fine after this

**Comment by cyp3rius** [comment]
Follow @shanebeeston  workaround, seems something being cached.

**Comment by anthonytison** [comment]
Yep it's good for me too. Thx
