### ISSUE TITLE
Role Permissions Strapi Community Edition

### ISSUE THREAD

**Issue by graphicfox** [VirtusLab-Open-Source/strapi-plugin-navigation#115]
Hello!

I looking for the possibility to let the Role Editor change the Navigation. But by default only the Content Type is editable. The menu itself  is not visible and cant be changed by a non Admin.

![image](https://user-images.githubusercontent.com/37541937/143900354-33465d46-24d6-49d2-aa4c-e1301a36e452.png)

**Comment by hrenaud** [comment]
I have the same problem, is it possible to make the navigation accessible and maintainable to the editor profile?

**Comment by cyp3rius** [comment]
@graphicfox @hrenaud, you have to edit permissions for Editor role to allow:
- Access
- Change

So those two you've got on attached screenshot must be checked.

**Comment by graphicfox** [comment]
Hey, sadly these options are inaccessible and not clickable.

**Comment by hrenaud** [comment]
@cyp3rius as @graphicfox said it, we are not allowed to change this configuration.

**Comment by hrenaud** [comment]
@graphicfox I worked around the problem by duplicating two entries in the database that were in the `strapi_permission` table.

You have to duplicate the row with the action `plugins::navigation.read` and put `2` in the `role` column. And the same for the row with the action `plugins::navigation.update`.

At this point, the checkboxes become checked and the menu accessible.

**Comment by graphicfox** [comment]
@hrenaud Thank you very much that did the trick. 

I will leave this open in the hope for an official fix 👍

**Comment by luxterful** [comment]
I have the same issue. I can see the Read and Update checkboxes in the role editor but i CANT edit them!
I use Strapi v4.0.7 and strapi-plugin-navigation v2.0.0
<img width="1512" alt="strapi-nav-permission-issue" src="https://user-images.githubusercontent.com/26602700/152880515-b52a9f77-fb20-4dec-8888-7c8545d304ed.png">

**Comment by edardev** [comment]
> @cyp3rius as @graphicfox said it, we are not allowed to change this configuration.

What does this mean? Custom plugins should be able to integrate or implement Roles and Permissions features, otherwise 😢

**Comment by cyp3rius** [comment]
Folks I've double checked it and officially Strapi Community is not supporting Plugin roles. This ability is enabled only for paid options where RBAC is extended, so every permission not related with Content Types (Collection, Single) is not going to be editable / accessible for Community.

See reference: https://docs.strapi.io/user-docs/latest/users-roles-permissions/configuring-administrator-roles.html (Caution section)

Let me discuss it with Strapi team directly to find a solution for Community which is not going to avoid the license and agreements (which we as a plugin authors are obligated to respect).

**Comment by yanniskadiri** [comment]
I had the chance to talk with @cyp3rius and he told me about this issue. Unfortunately, it's not compatible with our current offer. That being said, I'd like to tell you that our goal is to make RBAC part of the community edition in the future.
