### ISSUE TITLE
Content type entity not showing in dropdown

### ISSUE THREAD

**Issue by V1nga** [VirtusLab-Open-Source/strapi-plugin-navigation#116]
Hi, content type entity not showing in dropdown, i don't understand what is the problem.

Strapi version: 3.6.8
Navigation plugin version: 1.1.2

custom.js
``` js
module.exports = ({ env }) => ({
  plugins: {
    navigation: {
      relatedContentTypes: [
	'application::page.page'
      ],
      additionalFields: ['audience'],
      allowedLevels: 2,
      contentTypesNameFields: {
        'page': ['title']
      },
    },
  },
});
```

page.settings.json
``` json
{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "name": "page",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "uid": {
      "type": "uid",
      "targetField": "title"
    }
  }
}
```

![Screenshot_1](https://user-images.githubusercontent.com/43814565/143915187-26f42f97-df1e-4d5d-a7c1-576f49a5f2c5.jpg)

**Comment by georgeariton** [comment]
Hello,

I think this might be related to the fact that they recently removed the polymorphic relationships for the collections and this file might be the culprit "models/navigationItem.js"

**Comment by cyp3rius** [comment]
@V1nga follow please the updated documentation: https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation#content-type-model-relation-to-navigation-item

**Comment by georgeariton** [comment]
> @V1nga follow please the updated documentation: https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation#content-type-model-relation-to-navigation-item

I've just done a quick install of 3.6.8, created a collection named page and got this:
![image](https://user-images.githubusercontent.com/37028725/144204750-0235e611-5635-4344-902c-e45cbf4a1cd9.png)

Followed the instructions and tried to change the related content type with upper/lower case plural and singular variants... still doesn't work.

**Comment by georgeariton** [comment]
**Finally got this to work, but it's confusing**

1. All of the configurations must go in plugins.js:
`module.exports = ({ env }) => ({
  navigation: {
    relatedContentTypes: [
      'application::page.page'
    ],
    additionalFields: ['audience'],
    allowedLevels: 2,
    contentTypesNameFields: {
      'page': ['title']
    },
    gql: {
      navigationItemRelated: 'union NavigationRelated = Page',
    },
  },
});`
2. I've renamed all of the fields with **lowercase**
3. Added the entities before adding the menu

**Comment by V1nga** [comment]
> **Finally got this to work, but it's confusing**
> 
> 1. All of the configurations must go in plugins.js:
> 
> ```
> module.exports = ({ env }) => ({
>   navigation: {
>     relatedContentTypes: [
>       'application::page.page'
>     ],
>     additionalFields: ['audience'],
>     allowedLevels: 2,
>     contentTypesNameFields: {
>       'page': ['title']
>     },
>     gql: {
>       navigationItemRelated: 'union NavigationRelated = Page',
>     },
>   },
> });
> ```
> 
> 2. I've renamed all of the fields with **lowercase**
> 3. Added the entities before adding the menu

Thanks, it helped
