### ISSUE TITLE
Related field

### ISSUE THREAD

**Issue by V1nga** [VirtusLab-Open-Source/strapi-plugin-navigation#117]
Hi, how to make a related field in "render tree", as in "render rfr"? And why does the user bother with all his data in the "render tree" and "render flat"?

Strapi version: 3.6.8
Navigation plugin version: 1.1.2

RFR
![image](https://user-images.githubusercontent.com/43814565/144587522-2b4a37da-3330-4af3-8357-d82168a58bce.png)

TREE
![image](https://user-images.githubusercontent.com/43814565/144587952-8e65318e-eb4c-47bc-835b-e595b6c62c28.png)

**Comment by bayleak** [comment]
Got the same problem.
I think it should not be possible at all to expose user sensitive data via the api.
If this is not configurable  (at least i found nothing about this), this makes it impossible to use the plugin in a real world scenario.
I'm sure this is a bug and it is for sure a major security risk.

Or are we doing something wrong here?

**Comment by cyp3rius** [comment]
Investigation in progress.

**Comment by cyp3rius** [comment]
@bayleak @V1nga this issue has been already fixed in `v1.1.3` please upgrade your dependencies.

See: [release notes of v1.1.3](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/releases/tag/v1.1.3)
