### ISSUE TITLE
Add description field

### ISSUE THREAD

**Issue by hrenaud** [VirtusLab-Open-Source/strapi-plugin-navigation#118]
Could we have a description field (or any other name) that could be used to fill the title attribute of a link. This would be a plus for SEO and accessibility.

**Comment by cyp3rius** [comment]
To be considered in the next version, as for now you're able to extend the navigation item content type using Strapi Extensions: https://docs-v3.strapi.io/developer-docs/latest/development/admin-customization.html#customization-options
