### ISSUE TITLE
Navigation items with subitems and without linked internal contents

### ISSUE THREAD

**Issue by xetambda** [VirtusLab-Open-Source/strapi-plugin-navigation#124]
**Feature Request**

Hello!

thanks for this nice plugin.
At the moment a navigation item with subitems should be linked to an internal content. But sometimes a navigation item is just a container for other items. Is it possible to include navigation items that are not linked to internal content but can contain subitems?

**Comment by hrenaud** [comment]
@xetambda I got around the problem by creating two fake link types and the front end handles the behavior:
- http://internal.link which allows to add pages that are not created in Strapi -> http://internal.link/no-strapi-page
- http://root.link which allows you to have a sub-menu with links that appear on click or roll over, but which is not a link itself.

This is a workaround that works very well.
