### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'immutable'

### ISSUE THREAD

**Issue by mattmillen888** [VirtusLab-Open-Source/strapi-plugin-navigation#131]
I have installed the latest v2.0.0-beta.2 however now when i yarn build. i get the following issue from webpack

ModuleNotFoundError: Module not found: Error: Can't resolve 'immutable' in '/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/src/pages/DataManagerProvider'
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/neo-async/async.js:6883:13
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve 'immutable' in '/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/src/pages/DataManagerProvider'
  Parsed request is a module
  using description file: /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/package.json (relative path: ./admin/src/pages/DataManagerProvider)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/src/pages/DataManagerProvider/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/src/pages/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/src/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/node_modules doesn't exist or is not a directory
      looking for modules in /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules
        single file module
          using description file: /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/package.json (relative path: ./node_modules/immutable)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules/immutable doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules/immutable.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules/immutable.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules/immutable.react.js doesn't exist
        /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules/immutable doesn't exist
      /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules
        single file module
          using description file: /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/package.json (relative path: ./node_modules/immutable)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/immutable doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/immutable.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/immutable.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/immutable.react.js doesn't exist
        /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/immutable doesn't exist
      looking for modules in /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules
        single file module
          using description file: /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/package.json (relative path: ./node_modules/immutable)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules/immutable doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules/immutable.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules/immutable.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules/immutable.react.js doesn't exist
        /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules/immutable doesn't exist
      /Users/macbookpro/Sites/_training/_javascript/strapi/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/_training/_javascript/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/_training/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/node_modules doesn't exist or is not a directory
      /Users/macbookpro/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules
        single file module
          using description file: /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/package.json (relative path: ./node_modules/immutable)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules/immutable doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules/immutable.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules/immutable.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules/immutable.react.js doesn't exist
        /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules/immutable doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve 'immutable' in '/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/src/pages/DataManagerProvider'
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/neo-async/async.js:6883:13
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve 'immutable' in '/Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/src/pages/DataManagerProvider'
  Parsed request is a module
  using description file: /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/package.json (relative path: ./admin/src/pages/DataManagerProvider)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/src/pages/DataManagerProvider/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/src/pages/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/src/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/admin/node_modules doesn't exist or is not a directory
      looking for modules in /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules
        single file module
          using description file: /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/package.json (relative path: ./node_modules/immutable)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules/immutable doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules/immutable.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules/immutable.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules/immutable.react.js doesn't exist
        /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/strapi-plugin-navigation/node_modules/immutable doesn't exist
      /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules
        single file module
          using description file: /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/package.json (relative path: ./node_modules/immutable)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/immutable doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/immutable.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/immutable.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/immutable.react.js doesn't exist
        /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/immutable doesn't exist
      looking for modules in /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules
        single file module
          using description file: /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/package.json (relative path: ./node_modules/immutable)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules/immutable doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules/immutable.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules/immutable.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules/immutable.react.js doesn't exist
        /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/node_modules/immutable doesn't exist
      /Users/macbookpro/Sites/_training/_javascript/strapi/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/_training/_javascript/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/_training/node_modules doesn't exist or is not a directory
      /Users/macbookpro/Sites/node_modules doesn't exist or is not a directory
      /Users/macbookpro/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules
        single file module
          using description file: /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/package.json (relative path: ./node_modules/immutable)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules/immutable doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules/immutable.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules/immutable.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules/immutable.react.js doesn't exist
        /Users/macbookpro/Sites/_training/_javascript/strapi/strapi-cms-example-blog/backend/node_modules/@strapi/admin/node_modules/immutable doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by cyp3rius** [comment]
@mattmillen888 fix made by @Kronos66 releases as part of `v2.0.0-beta.3`.
