### ISSUE TITLE
Content Type Blank

### ISSUE THREAD

**Issue by mattmillen888** [VirtusLab-Open-Source/strapi-plugin-navigation#133]
I have everything installed now without bugs. (Thank-you for the prompt updates on the install issues! :))

What i cant work out if this is a configuration issue on my part or another bug.

when i go to UI Navigation in admin panel. I go to create first navigation item but save is greyed out and Content Type has nothing populated. 

do i need to do something else or create a special content type to show on dropdown?
<img width="882" alt="example-navigation-url" src="https://user-images.githubusercontent.com/25214970/148671394-c50c484c-443d-49a2-9af8-de2184af0ec1.png">

Just so you know im using the standard nextjs corporate template here https://github.com/strapi/starters-and-templates/tree/main/packages/starters/next-corporate

I have not customised anything on this so if it works for you on this it should work for me :)

**Comment by cyp3rius** [comment]
Seems like missing configuration for Content Types. Have you followed the Readme.md?

**Comment by ltsNotMike** [comment]
I've updated the configuration section in the docs. I hope this will help with the bug.

**Comment by andreyluchianic** [comment]
same here 
<img width="1680" alt="Screenshot 2022-01-10 at 23 07 49" src="https://user-images.githubusercontent.com/88837148/148839650-50ebdf32-87e8-4bee-b551-042e566e8737.png">
<img width="907" alt="Screenshot 2022-01-10 at 23 07 57" src="https://user-images.githubusercontent.com/88837148/148839661-111b8ddc-d0ee-474f-a35d-00912a741e57.png">

**Comment by cyp3rius** [comment]
Closing, reopen if needed.

**Comment by ThomasFKJorna** [comment]
I have the same problem and can't manage to figure out how to resolve it. I tried a lot of different combinations for all these but no dice.

./config/plugins.js
```js
module.exports = ({ env }) => ({
  navigation: {
    additionalFields: ["audience"],
    allowedLevels: 2,
    contentTypesNameFields: {
      blog_posts: ["title"],
    },
  },
});
```

./src/api/blog-post/content-types/blog-post
```js
{
  "kind": "collectionType",
  "collectionName": "blog_posts",
  "info": {
    "singularName": "blog-post",
    "pluralName": "blog-posts",
    "displayName": "Blog Post"
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string",
      "required": true
    }
  }
}
```

Am I supposed to use something different than the `collectionName` here? I've tried singular and plural names, but no luck.

## Screenshot
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/21983833/149318355-9cf9b6e4-e256-4604-9f7a-4cb0a444fca2.png">

**Comment by cyp3rius** [comment]
@ThomasFKJorna have you tried `api::blog-post.blog-post` ?

**Comment by ThomasFKJorna** [comment]
The UUID is indeed "api::blog-post.blog-post"


Same result for this configuration:

module.exports = ({ env }) => ({
  navigation: {
    additionalFields: ["audience"],
    allowedLevels: 2,
    contentTypes: [
      "api::blog-post.blog-post",
      "api::jote-article.jote-article",
      "api::user.user",
      "api::article.article",
    ],
    contentTypesNameFields: {
      "api::blog-post.blog-post": ["title"],
      blog_posts: ["title"],
    },
  },
});


Screenshot

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/21983833/149321653-37868c73-3323-4c34-8adf-b331cf830131.png">

Also I am not able to build the application on node v14 due to some dependency issues with @strapi upload plugin, but that might be resolvable.

**Comment by ltsNotMike** [comment]
In strapi v4 structure of the config file is changed slightly 
```js
module.exports = ({ env }) => ({
  navigation: {
    config: { <your config here> }
  }
});
```
Your config has proper fields and values but it's never used because of the wrong structure.

**Comment by cyp3rius** [comment]
Yep, we will update the docs. Try what @ltsNotMike advice.

**Comment by ThomasFKJorna** [comment]
Amazing, thank you so much for the quick help!

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/21983833/149324436-503820f9-fea8-4811-b6ba-a35e3ac7fea0.png">

**Comment by ThomasFKJorna** [comment]
Just while I have you here, a quick Q: if I understand this plugin correctly, you are able to design navigation layouts to be consumed by some frontend application, not define a new navigation structure for use in the Strapi admin panel, right?

I was under the impression it was the latter at first, but I think I may have been mistaken.

**Comment by cyp3rius** [comment]
Yep, you're defining the navigation structure for your client application.
