### ISSUE TITLE
v2.0.0-beta.3 - Error on saving with external links

### ISSUE THREAD

**Issue by Tiagogv** [VirtusLab-Open-Source/strapi-plugin-navigation#135]
Strapi Version: 4.0.3

The following error is thrown on frontend when having a NavigationItem with an External Url and clicking on Save button. 
It impossible to configure External links using the Admin UI because of this.

`
[Error] TypeError: undefined is not an object (evaluating 'related.value')
	transformItemToRESTPayload (my-plugin.chunk.js:875)
	map
	transformToRESTPayload (my-plugin.chunk.js:918)
	handleSave (vendors-node_modules_strapi-plugin-navigation_admin_src_pages_View_index_js.chunk.js:2010:137)
	handleClick (Button.js:73)
	callCallback (main.bundle.js:146338)
	dispatchEvent
	invokeGuardedCallbackDev (main.bundle.js:146387)
	invokeGuardedCallback (main.bundle.js:146449)
	invokeGuardedCallbackAndCatchFirstError (main.bundle.js:146463)
	executeDispatch (main.bundle.js:150636)
	processDispatchQueueItemsInOrder (main.bundle.js:150668)
	processDispatchQueue (main.bundle.js:150681)
	dispatchEventsForPlugins (main.bundle.js:150692)
	batchedEventUpdates$1 (main.bundle.js:164784)
	batchedEventUpdates (main.bundle.js:146138)
	dispatchEventForPluginEventSystem (main.bundle.js:150900)
	attemptToDispatchEvent (main.bundle.js:148398)
	dispatchEvent (main.bundle.js:148317)
	dispatchEvent
	unstable_runWithPriority (main.bundle.js:209358)
	discreteUpdates$1 (main.bundle.js:164801)
	discreteUpdates (main.bundle.js:146149)
	dispatchDiscreteEvent (main.bundle.js:148282)
	dispatchDiscreteEvent
`

**Comment by ltsNotMike** [comment]
@Tiagogv Thank you for pointing out this issue. I've committed a fix for this bug so the next beta version shouldn't have any more problems with external links.

**Comment by ltsNotMike** [comment]
I will close the issue since the new release ( v2.0.0-beta.1 ) is ready. Please feel free to reopen if needed.
