### ISSUE TITLE
Plugin not showing up after fresh installation.

### ISSUE THREAD

**Issue by KrisKnez** [VirtusLab-Open-Source/strapi-plugin-navigation#141]
I am having a problem with the installation of this plugin.

I just did this
`yarn create strapi-app my-project --quickstart`
and then
`cd my-project`
`yarn add strapi-plugin-navigation@latest`
`yarn develop --watch-admin`

After setting up my account and going to the plugins page, navigation is not listed as a plugin there.

What may be the problem? Am I missing a step?

UPDATE: My toolchan version which might help resolving the problem
```
PS C:\dev\test-strapi3> volta list
⚡️ Currently active tools:

    Node: v14.18.3 (default)
    npm: v8.1.1 (default)
    Yarn: v1.22.17 (default)
    Tool binaries available:
        analyze (default)
        create-next-app (default)
        firebase (default)
        gatsby (default)
        ghost (default)
        lt (default)
        ngrok (default)
        yalc (default)
```

**Comment by cyp3rius** [comment]
I assume plugin hasn't been enabled in your configuration. Check please the **Configuration** section of our readme, you must add `enable: true` I guess.

**Comment by KrisKnez** [comment]
The way the plugin is detected is that strapi searches through `node_modules` for plugins and I can verify that `strapi-plugin-navigation` is present there which means I have correctly added it via yarn.

I have also installed the latest version of strapi for which this plugin was test (4.0.5) and it is also not getting detected.

**Comment by KrisKnez** [comment]
> I assume plugin hasn't been enabled in your configuration. Check please the **Configuration** section of our readme, you must add `enable: true` I guess.

When I add the `enable: true`, the file looks like this:

```
module.exports = ({ env }) => ({
  navigation: {
    enabled: true,
  },
});
```

And I cannot build the server, I get the following error:

```
PS C:\dev\test-strapi3> yarn build
yarn run v1.22.17
warning ..\package.json: No license field
$ strapi build
Building your admin UI with development configuration ...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:162:9)
    at C:\dev\test-strapi3\node_modules\@strapi\admin\index.js:181:33
    at Array.filter (<anonymous>)
    at createCacheDir (C:\dev\test-strapi3\node_modules\@strapi\admin\index.js:179:6)
    at Object.build (C:\dev\test-strapi3\node_modules\@strapi\admin\index.js:54:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by KrisKnez** [comment]
The only solution regarding the `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined` problem I have found is:

https://github.com/strapi/strapi-starter-react-blog/issues/7

But that is in no way related to my case, my project nor `@strapi/strapi` nor `strapi-plugin-navigation` use `react-scripts` or `react-dev-utils` as far as I see...

**Comment by KrisKnez** [comment]
Running `yarn check` gives me this output but I don't know if it's related...
```
PS C:\dev\test-strapi3> yarn check
yarn check v1.22.17
warning "@strapi/admin#@strapi/design-system##styled-components@^5.2.1" could be deduped from "5.3.3" to "styled-components@5.3.3"
error "strapi-helper-plugin#react-dom" not installed
warning "strapi-helper-plugin#react-router-dom#react@>=15" could be deduped from "17.0.2" to "react@17.0.2"
error "@strapi/admin#react-select" not installed
error "@strapi/admin#react-virtualized" not installed
error "react-virtualized#dom-helpers" not installed
error "strapi-helper-plugin#react-dom#scheduler" is wrong version: expected "0.19.1", got "0.20.2"
warning "strapi-helper-plugin#@buffetjs/styles#react-dates#react-with-styles@^4.1.0" could be deduped from "4.2.0" to "react-with-styles@4.2.0"
warning "strapi-helper-plugin#@buffetjs/styles#react-tooltip#react@>=16.0.0" could be deduped from "17.0.2" to "react@17.0.2"
error "react-select#react-transition-group" not installed
warning "strapi-helper-plugin#@buffetjs/core#reactstrap##react@>=16.3.0" could be deduped from "17.0.2" to "react@17.0.2"
error "react-select#react-transition-group#dom-helpers" not installed
warning "strapi-helper-plugin#react-dates#react-outside-click-handler#react@^0.14 || >=15" could be deduped from "17.0.2" to "react@17.0.2"
warning "strapi-helper-plugin#react-dates#react-portal#react@^15.0.0-0 || ^16.0.0-0 || ^17.0.0-0" could be deduped from "17.0.2" to "react@17.0.2"
warning "strapi-helper-plugin#@buffetjs/core#reactstrap#react-transition-group#react@>=16.6.0" could be deduped from "17.0.2" to "react@17.0.2"
warning "strapi-helper-plugin#react-dates#react-with-styles#react@>=0.14" could be deduped from "17.0.2" to "react@17.0.2"
info Found 18 warnings.
error Found 15 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

**Comment by cyp3rius** [comment]
Check please you `package.json` file, probably the @latest has installed v3 compatible version. We must fix it.

The most recent version: `2.0.0-rc.1`

**Comment by KrisKnez** [comment]
> Check please you `package.json` file, probably the @latest has installed v3 compatible version. We must fix it.
> 
> The most recent version: `2.0.0-rc.1`

You are right!
```
"dependencies": {
    "@strapi/plugin-i18n": "4.0.5",
    "@strapi/plugin-users-permissions": "4.0.5",
    "@strapi/strapi": "4.0.5",
    "sqlite3": "5.0.2",
    "strapi-plugin-navigation": "^1.1.4"
  },
```

I have `Strapi `version 4 installed and  `strapi-plugin-navigation` Version 1 which is for `Strapi `version 3.x.
Do you recommend me use Strapi version 3 or `strapi-plugin-navigation` version 2? Because `strapi-plugin-navigation` version 2 is in beta according to https://www.npmjs.com/package/strapi-plugin-navigation

**Comment by cyp3rius** [comment]
The v4 compatible version is already in RC so we recommend to use it. No further changes is planned, we are collecting test feedback only and going to release first major version soon :)

Use please `2.0.0-rc.1` and if any issue occurs report it to us.

**Comment by KrisKnez** [comment]
There is no `2.0.0-rc.1`. The latest version 2 is `v2.0.0-beta.5`

**Comment by cyp3rius** [comment]
By some reason, package hasn't published automatically. Done that manually now, and should be ok.
