### ISSUE TITLE
How doest it work with multiple menu ?

### ISSUE THREAD

**Issue by Jimmylet** [VirtusLab-Open-Source/strapi-plugin-navigation#142]
Thank you for this plugin which is very clean!

I am trying the latest version (for Strapi v4).

But I don't quite understand how it works.

I would like to create several menus:

- Main navigation
- Footer navigation

In "UI Navigation", when I add links, I don't know how to differentiate between the links that will go in the footer or those that will go in the main navigation.

I noticed a "Navigation" collection.

But it's not very clear. Can you explain to me how it works?

Thank you

**Comment by ltsNotMike** [comment]
Hello @Jimmylet
We are happy to hear that you enjoy the plugin so far. The plugin at this point only supports one navigation per application. Right now the only possibility to customize how navigation is consumed is the introduction of the audience field. You can read about it in the documentation. We plan to add support for multiple navigations not far into the future so please feel free to follow our project for updates on that.

**Comment by cyp3rius** [comment]
To put more light into it. Upcoming week we are planning to publish detailed roadmap and it is not yet said we won't include the multiple navigations before non-RC release ;)

**Comment by Jimmylet** [comment]
> To put more light into it. Upcoming week we are planning to publish detailed roadmap and it is not yet said we won't include the multiple navigations before non-RC release ;)

This is great news. Strapi is moving in the right direction and I think your plugin could be a "must-have" in the future.

**Comment by cyp3rius** [comment]
@Jimmylet feature has been released as part of `v2.0.0` final release 💪
