### ISSUE TITLE
[CU-21ungpa] Get page by path defined in UI Navigation

### ISSUE THREAD

**Issue by motion-work** [VirtusLab-Open-Source/strapi-plugin-navigation#146]
Is it possible to query (Graphql or REST) a page by the path defined with UI Navigation Plugin? I'm trying to create a Main Navigation Menu within Nuxt.js.

<img width="228" alt="Screenshot 2022-02-04 at 14 34 37" src="https://user-images.githubusercontent.com/11538632/152537782-25efeb7c-db04-49b9-be64-46db9b31cec9.png">

**Comment by cyp3rius** [comment]
At this very moment no, but we're happy to pick it up for one of upcoming versions or maybe you can contribute to it?

**Comment by cyp3rius** [comment]
Moved to backlog for `v2.0.2` as `[CU-21ungpa]`
