### ISSUE TITLE
Format API to match default Strapi response

### ISSUE THREAD

**Issue by Kinbaum** [VirtusLab-Open-Source/strapi-plugin-navigation#151]
Hello, I am using the Strapi SDK as an interface between my front end and the data. This let's me use methods such as `find` `findOne` etc.

Would it be possible to modify the navigation response so the the information is nested under the `data` and `meta` keys?
This would better align to the contract that the SDK expects when querying a collection.

I've extended this for the time being to play well with Typescript and the SDK.

```js
plugin.controllers.navigation.render = async ctx => {
    const { params, query } = ctx;
    const type = Array.isArray(query.fields) ? query.fields[0] : query.fields;
    const data = await plugin.services.navigation({ strapi }).render(params.idOrSlug, type);

    return {
        data,
        meta: {}
    };
};
```

This allows me to use the SDK like so on the UI:

```js
strapi.findOne<Navigation[]>('navigation/render', 'my-navigation', {
  fields: [ 'tree' ]
})
```

**Comment by cyp3rius** [comment]
Hello @Kinbaum, plugin provides custom functionality and its not only a Collection provider. Thats why its not following the Strapi SDK.

**Comment by Kinbaum** [comment]
Fair enough
