### ISSUE TITLE
Popup about autoReload feature in Production

### ISSUE THREAD

**Issue by luxterful** [VirtusLab-Open-Source/strapi-plugin-navigation#166]
I get a popup about an disabled autoReload Feature every time i open Content Type Builder or UI Navigation in Production.

![image](https://user-images.githubusercontent.com/26602700/156200419-52f40e22-37ed-4382-99ec-18fe62cfa36d.png)

![image](https://user-images.githubusercontent.com/26602700/156200585-70bc91d0-8d37-4f43-ba81-dcb6ed7708d6.png)

I run Strapi 4.1.1 and this Plugin in 2.0.5

**Comment by cyp3rius** [comment]
@luxterful this is native strapi feature which we are using. Please find a help on global channel. Its not plugin specific.

It appears because our plugin requires restart if you are changing some settings which are impacting GQL.

**Comment by luxterful** [comment]
I did not use GQL features at all.

**Comment by cyp3rius** [comment]
@luxterful Two, but plug-in supports it :) Thats the reason why you see such warning. It is not affecting plugin itself, or am I wrong and you are not able to use it at all?
