### ISSUE TITLE
Can't create internal links: "no content type to select"

### ISSUE THREAD

**Issue by lansolo99** [VirtusLab-Open-Source/strapi-plugin-navigation#170]
Hi,

Using the latest Strapi version (v.4.1.3), I have browsed the whole doc and other similar issues but can't figure out how to get my content type within the drop-down, which is greyed out : 

<img width="600" alt="Screenshot 2022-03-11 at 10 49 48" src="https://user-images.githubusercontent.com/10405016/157845815-f09b69a1-f1c0-4dbd-a8e1-f123625246f3.png">

I brought a custom config in `plugins.js` and properly set my content-types (and rebuild all the time) : 

<img width="571" alt="Screenshot 2022-03-11 at 11 05 37" src="https://user-images.githubusercontent.com/10405016/157846213-86f57e0c-2d05-4f44-97d4-e5b83fba2d9f.png">

My content-types contains published documents and their public roles have been set so that API calls work properly.
My collections have `name` fields, for example, test:

<img width="302" alt="Screenshot 2022-03-11 at 11 09 41" src="https://user-images.githubusercontent.com/10405016/157846904-08e3a5c7-14a4-4519-9296-06fe9bf4c0ca.png">

I don't know if I'm missing some points but any help will be appreciated.
Thanks!

**Comment by ltsNotMike** [comment]
Hello @lansolo99, 

Since version 2.0.3 of our plugin, all settings are set through the settings page. The `plugins.js` file is used as a backup, so if you want to synchronize it with your application you have to restore settings through the settings page. More information about it is placed in [docs](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation#-configuration). Hope this will help 🙂

**Comment by cyp3rius** [comment]
@lansolo99 please go to `Settings -> Navigation Plugin -> Configuration` and click "Restore". It will then load plugin configuration from file to **Strapi DB Store**, because as @ltsNotMike said once Settings page has been introduced, also the way of configuration changed to more user friendly.

**Comment by lansolo99** [comment]
@cyp3rius Ah thanks, my bad, I confused the navigation plugin panel UI with the navigation plugins settings panel 🤭.
Sorry to have cluttered the issue board..
It's working properly now, I close the issue.
