### ISSUE TITLE
Unable to install/build - @strapi/design-system/Text not found

### ISSUE THREAD

**Issue by timothybennette8** [VirtusLab-Open-Source/strapi-plugin-navigation#173]
Apologies if this is not the right place to ask this - I'm having trouble installing the plugin.

I've tried installing the plugin via yarn and it doesn't run smoothly:
<details>
<summary>Yarn add warnings</summary>

[1/5] Validating package.json...

[2/5] Resolving packages...
warning strapi-plugin-navigation > react-intl > intl-messageformat-parser@5.5.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
warning strapi-plugin-navigation > react-intl > intl-messageformat > intl-messageformat-parser@5.5.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
warning strapi-plugin-navigation > react-intl > @formatjs/intl-utils@2.3.0: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
warning strapi-plugin-navigation > react-intl > @formatjs/intl-listformat > @formatjs/intl-utils@2.3.0: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
warning strapi-plugin-navigation > react-intl > @formatjs/intl-displaynames > @formatjs/intl-utils@2.3.0: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
warning strapi-plugin-navigation > react-intl > @formatjs/intl-relativetimeformat > @formatjs/intl-utils@2.3.0: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
warning strapi-plugin-navigation > react-intl > @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
warning strapi-plugin-navigation > react-intl > @formatjs/intl-unified-numberformat > @formatjs/intl-utils@2.3.0: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
warning strapi-plugin-navigation > reactstrap > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@strapi/plugin-seo > eslint-plugin-react-hooks@4.3.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.5" has unmet peer dependency "formik@^2.2.6".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.5" has unmet peer dependency "immer@9.0.6".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.5" has unmet peer dependency "qs@6.10.1".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.5" has unmet peer dependency "react-select@^4.0.2".
warning "@strapi/plugin-users-permissions > grant-koa@5.4.8" has unmet peer dependency "koa@>=2.0.0".
warning "@strapi/plugin-users-permissions > react-redux@7.2.3" has unmet peer dependency "redux@^2.0.0 || ^3.0.0 || ^4.0.0-0".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin > mini-css-extract-plugin@2.4.4" has unmet peer dependency "webpack@^5.0.0".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
warning "@strapi/strapi > @strapi/admin > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning "@strapi/strapi > @strapi/admin > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning "strapi-plugin-sitemap > redux-thunk@2.4.1" has unmet peer dependency "redux@^4".
warning " > strapi-plugin-slugify@2.2.1" has unmet peer dependency "@strapi/utils@^4.0.7".
warning " > strapi-plugin-slugify@2.2.1" has unmet peer dependency "lodash@^4.17.21".
warning " > strapi-plugin-slugify@2.2.1" has unmet peer dependency "yup@^0.32.9".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
success Saved lockfile.
warning Workspaces can only be enabled in private projects.
success Saved 16 new dependencies.
info Direct dependencies
└─ strapi-plugin-navigation@2.0.5
info All dependencies
├─ @formatjs/intl-numberformat@5.7.6
├─ @formatjs/intl-relativetimeformat@4.5.16
├─ @formatjs/intl-unified-numberformat@3.3.7
├─ @types/invariant@2.2.35
├─ bad-words@3.0.4
├─ badwords-list@1.0.0
├─ classnames@2.3.1
├─ gud@1.0.0
├─ intl-format-cache@4.3.1
├─ intl-messageformat-parser@5.5.1
├─ popper.js@1.16.1
├─ shallow-equal@1.2.1
├─ slugify@1.6.5
├─ strapi-plugin-navigation@2.0.5
├─ typed-styles@0.0.7
└─ warning@4.0.3
Done in 13.86s.

</details>
I recognise that some of those relate to other plugins (installed and working), but other than SEO, Slugify, and Sitemap it's a box-fresh Strapi installation.

Yarn build returns this error:
<details>
<summary>Build error message</summary>

ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/Text' in /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/View/components/NavigationItemPopup'
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/Compilation.js:2011:28
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/home/tim/dev/strapi/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/home/tim/dev/strapi/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /home/tim/dev/strapi/backend/node_modules/neo-async/async.js:6883:13
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/home/tim/dev/strapi/backend/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /home/tim/dev/strapi/backend/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /home/tim/dev/strapi/backend/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/tim/dev/strapi/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/Text' in '/home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/View/components/NavigationItemPopup'
  Parsed request is a module
  using description file: /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/package.json (relative path: ./admin/src/pages/View/components/NavigationItemPopup)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/View/components/NavigationItemPopup/node_modules doesn't exist or is not a directory
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/View/components/node_modules doesn't exist or is not a directory
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/View/node_modules doesn't exist or is not a directory
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/node_modules doesn't exist or is not a directory
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/node_modules doesn't exist or is not a directory
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/node_modules doesn't exist or is not a directory
      looking for modules in /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/node_modules
        /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/node_modules/@strapi/design-system doesn't exist
      /home/tim/dev/strapi/backend/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/tim/dev/strapi/backend/node_modules
        existing directory /home/tim/dev/strapi/backend/node_modules/@strapi/design-system
          using description file: /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/package.json (relative path: .)
            using description file: /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/package.json (relative path: ./Text)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/Text doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/Text.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/Text.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/Text.react.js doesn't exist
              as directory
                /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/Text doesn't exist
      /home/tim/dev/strapi/node_modules doesn't exist or is not a directory
      /home/tim/dev/node_modules doesn't exist or is not a directory
      /home/tim/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/tim/dev/strapi/backend/node_modules/@strapi/admin/node_modules
        /home/tim/dev/strapi/backend/node_modules/@strapi/admin/node_modules/@strapi/design-system doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/Text' in '/home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/View/components/NavigationItemPopup'
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/Compilation.js:2011:28
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/home/tim/dev/strapi/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/home/tim/dev/strapi/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /home/tim/dev/strapi/backend/node_modules/neo-async/async.js:6883:13
    at /home/tim/dev/strapi/backend/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/home/tim/dev/strapi/backend/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /home/tim/dev/strapi/backend/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /home/tim/dev/strapi/backend/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/tim/dev/strapi/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/Text' in '/home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/View/components/NavigationItemPopup'
  Parsed request is a module
  using description file: /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/package.json (relative path: ./admin/src/pages/View/components/NavigationItemPopup)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/View/components/NavigationItemPopup/node_modules doesn't exist or is not a directory
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/View/components/node_modules doesn't exist or is not a directory
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/View/node_modules doesn't exist or is not a directory
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/pages/node_modules doesn't exist or is not a directory
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/src/node_modules doesn't exist or is not a directory
      /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/admin/node_modules doesn't exist or is not a directory
      looking for modules in /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/node_modules
        /home/tim/dev/strapi/backend/node_modules/strapi-plugin-navigation/node_modules/@strapi/design-system doesn't exist
      /home/tim/dev/strapi/backend/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/tim/dev/strapi/backend/node_modules
        existing directory /home/tim/dev/strapi/backend/node_modules/@strapi/design-system
          using description file: /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/package.json (relative path: .)
            using description file: /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/package.json (relative path: ./Text)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/Text doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/Text.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/Text.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/Text.react.js doesn't exist
              as directory
                /home/tim/dev/strapi/backend/node_modules/@strapi/design-system/Text doesn't exist
      /home/tim/dev/strapi/node_modules doesn't exist or is not a directory
      /home/tim/dev/node_modules doesn't exist or is not a directory
      /home/tim/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/tim/dev/strapi/backend/node_modules/@strapi/admin/node_modules
        /home/tim/dev/strapi/backend/node_modules/@strapi/admin/node_modules/@strapi/design-system doesn't exist

</details>

I've tried updating @strapi/design-system but still no Text.js.
I'm a bit stumped as to what to do (please forgive my novice abilities), and any advice as to where I'm going wrong would be greatly appreciated!

OS: Ubuntu & Windows 10
Node: 16.14.1
Yarn: 1.22.15
Strapi: 4.1.5

**Comment by xantiagoma** [comment]
I'm having the same issue once I updated to 4.1.5.

**Comment by mig-25** [comment]
yeah, same here... it worked when I was on strapi 4.1.3 but not when I upgraded strapi to 4.1.5. As @timothybennette8 I tried too to install @strapi/design-system.
I am on Mac OS Monterey 12.2.1
Node v16.13.0
Yan 1.22.17
Strapi 4.1.5

**Comment by cyp3rius** [comment]
Folks, fixed as part of `v2.0.6`
