### ISSUE TITLE
Drag & Drop not working in Firefox

### ISSUE THREAD

**Issue by cortopy** [VirtusLab-Open-Source/strapi-plugin-navigation#177]
For quite some time I just thought that I was doing something wrong with drag & drop. I use Firefox as my main browser and it turns out that Drag & Drop only works in Chrome!

I'm not sure why this could be, but if it's not likely to be fixed, it could maybe mentioned in the README?

**Comment by cyp3rius** [comment]
Fixed as part of `v2.0.8`

**Comment by artzyres** [comment]
Currently experiencing the same issue with the latest version, drag & drop works in Chrome, but seems not to work in Firefox.
Firefox version is 102.0
Plugin version is 2.1.0
