### ISSUE TITLE
save button is disabled for single type items

### ISSUE THREAD

**Issue by stengard** [VirtusLab-Open-Source/strapi-plugin-navigation#180]
Since the last release ([2.7.0](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/releases/tag/v2.0.7)) it is no longer possible to save a navigation item when the selected `contentType` is a single type.

The problem is that this code does not take into account that single types are internal but does not have any related data in the form object.

```javascript
  const submitDisabled =
    (form.type === navigationItemType.INTERNAL && isNil(get(form, `${inputsPrefix}related`))) ||
    (form.type === navigationItemType.WRAPPER && isNil(get(form, `${inputsPrefix}title`)));
```

I think there are some other places where we need to check for single types as well where it's expecting related property

The button I'm talking about is "Save" in the bottom right corner.

![image](https://user-images.githubusercontent.com/5670109/159673486-cfb0fe85-5536-44e4-b530-11c4a4bc8dbb.png)

**Comment by cyp3rius** [comment]
Fixed as part of `v2.0.8`
