### ISSUE TITLE
issues with single types

### ISSUE THREAD

**Issue by stengard** [VirtusLab-Open-Source/strapi-plugin-navigation#182]
There still seems to be some issues with single types.

since 2.0.8, it's now again possible to create a single type navigation item (thanks 👍)

There still are some problems though.

#### Single Types are always shown as draft. 

It does not seem that single types have `relatedRef.publishedAt`. I think that's why.

![chrome_sKxSRdByBk](https://user-images.githubusercontent.com/5670109/159714160-f279d198-00aa-4f6f-a666-6d3377c227c2.png)

#### It's impossible to save the "main navigation" when it includes an single type item.

I think it's because `structureHasErrors` is true due to `isRelationCorrect` returning false for single types since they do not have `related`. There might be more to this because if you bypass the disabled button and save anyway, the navigation item is missing in the response.

![chrome_QDXBH6j9Ko](https://user-images.githubusercontent.com/5670109/159714283-5d3c4f5d-213e-4219-b46d-092e25ac33d6.png)

To reproduce just add a navigation item with a single type.

**Comment by cyp3rius** [comment]
Released as part of `v2.0.9`
