### ISSUE TITLE
Missing Query field Render in GraphQL Strapi V4

### ISSUE THREAD

**Issue by maxsv01** [VirtusLab-Open-Source/strapi-plugin-navigation#183]
I have enable access for render and renderChild in public permissions, but I haven't seen this query field in GraphQL Playground.

![image](https://user-images.githubusercontent.com/23117796/159783493-2dcea911-390f-4d15-84f1-f136bd67e522.png)
![image](https://user-images.githubusercontent.com/23117796/159784306-dd36e5a7-f7a2-4792-9ada-b3bcecf9f384.png)
![image](https://user-images.githubusercontent.com/23117796/159784466-66b73b14-a6ba-47f8-a389-83742bc3be78.png)
![image](https://user-images.githubusercontent.com/23117796/159786526-8fa1a28a-deb3-4388-950f-e350a4342081.png)

But in API it works OK.

I don't use plugin.js or some custom.js file for plugins settings.

I use the latest version of Strapi V4, Node 14.18.1, Npm 8.1.1 and strapi-plugin-navigation 2.0.8.

Can you help me? 

Thanks

**Comment by cyp3rius** [comment]
@maxsv01 there is a trick to do (we hope to solve it in the future or maybe Strapi will introduce plugin initialization ordering).

```js
module.exports = {
  'navigation': { enabled: true },
  'graphql': { enabled: true },
};
```

Put this pleas in your `config/plugins.js` and should work. Plugins are rendered by the installation order probably by default (that's my guess) but to use GQL with Navigation you must initialize our plugin.

**Comment by cyp3rius** [comment]
Closing as for now because of inactivity. If my last suggestion won't solve your issue, re-open please.

**Comment by abdhass** [comment]
> @maxsv01 there is a trick to do (we hope to solve it in the future or maybe Strapi will introduce plugin initialization ordering).
> 
> ```js
> module.exports = {
>   'navigation': { enabled: true },
>   'graphql': { enabled: true },
> };
> ```
> 
> Put this pleas in your `config/plugins.js` and should work. Plugins are rendered by the installation order probably by default (that's my guess) but to use GQL with Navigation you must initialize our plugin.

i had the same issue and this fixed it. thanks

**Comment by lgt** [comment]
this workaround not seems to work in my case

plugins.js

```
module.exports = () => ({
  // ...
  navigation: {
      enabled: true,
  },
  graphql: {
    enabled: true,
    config: {
      endpoint: "/graphql",
      shadowCRUD: true,
      playgroundAlways: false,
      depthLimit: 7,
      amountLimit: 100,
      apolloServer: {
        tracing: false,
      },
    },
  },
});
```

I get:  ` "message": "Cannot query field \"renderNavigation\" on type \"Query\".",`

using strapi 4.6.2
plugin version: 2.2.4
