### ISSUE TITLE
Settings page fails to render when using content types from a plugin

### ISSUE THREAD

**Issue by aevarisak** [VirtusLab-Open-Source/strapi-plugin-navigation#184]
Hi first of all thank you for this great plugin

But I have this issue where I have content types coming from a custom plugin. These content types are filtered out in the settings page.

Adding the plugin content types like this in config works fine and the navigation can be configured and rendered.

```js
  navigation: {
    enabled: true,
    config: {
      additionalFields: ["audience"],
      contentTypes: ["plugin::myplugin.contenttype"],
      contentTypesNameFields: {
        "plugin::myplugin.contenttype": ["name"],
      },
      allowedLevels: 2,
    },
  },
```

But when loading the settings page an error occurs since this content type is filtered out [here](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/blob/983728cb6b392af7051b171ce9741bdab5c46657/admin/src/pages/SettingsPage/index.js#L111) only allowing content types that include `api::` to be used.

I could create a PR for this but I'm not sure what would be the best option to configure this. Perhaps an array of allowed uids in the config similar to the `contentTypes` option?

**Comment by cyp3rius** [comment]
Introduced in `v2.0.11`
