### ISSUE TITLE
Unable to create navigation with single type in 2.0.9

### ISSUE THREAD

**Issue by cortopy** [VirtusLab-Open-Source/strapi-plugin-navigation#190]
I've found another regression with 2.0.9. Single types were working for me before but now I can't create any

If I create a new navigation item with single content type, I experience the following issues:

- The title of the related item overrides the title I've written
- I can't edit the title afterwards
- The relation seems lost, as when I click on edit it doesn't tell me which content it's related to

**Comment by cortopy** [comment]
yes, I reverted to 2.0.8 as it was giving some issues. It's just a single content type, nothing unusual. It has the property `name` though, which I don't know if it was overriding something in the new version

I realised that it was even failing to save the item, and maybe that's why the frontend was behaving weirdly

**Comment by cyp3rius** [comment]
Does your single type use Publish Flow?

**Comment by cortopy** [comment]
None of my single types are using publish flow at the moment

**Comment by cyp3rius** [comment]
Ok so Thats the missed piece seems. Should be fixed by night today.

**Comment by cyp3rius** [comment]
@cortopy `v2.0.10` has been just released. Check please if fixed your issue (I've tested it with number of single types and works).

If yes, please close the issue.

**Comment by cortopy** [comment]
@cyp3rius all working great with 2.0.10. Thanks for this!
