### ISSUE TITLE
Cannot load the Navigation part of Strapi Dashboard

### ISSUE THREAD

**Issue by webburo-spring** [VirtusLab-Open-Source/strapi-plugin-navigation#200]
The navigation section under settings works fine, but if I try to open the seperate Navigation panel it doesn't load. On the server I get the following error:

```
error: select `t0`.* from `navigations` as `t0` limit -1 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1
```

Error happens at async Object.get (/node_modules/strapi-plugin-navigation/server/services/navigation.js:33:24)

I am using the following dependencies for my strapi app:
```
  "devDependencies": {},
  "dependencies": {
    "@strapi/design-system": "^0.0.1-alpha.74",
    "@strapi/icons": "^0.0.1-alpha.74",
    "@strapi/plugin-graphql": "4.1.5",
    "@strapi/plugin-i18n": "4.1.5",
    "@strapi/plugin-users-permissions": "4.1.5",
    "@strapi/provider-email-sendgrid": "4.1.5",
    "@strapi/strapi": "4.1.5",
    "mysql": "2.18.1",
    "react": "^17.0.2",
    "strapi-plugin-comments": "2.0.10",
    "strapi-plugin-navigation": "2.0.9"
  },
```

About a week ago everything worked fine. I changed the version of a few dependencies meanwhile, but I cannot get it working again by reverting to older versions.
I am still able to use the navigation API on my website, so that part stil works.

**Comment by webburo-spring** [comment]
Just tried the latest version of the plugin and it works! Thanks. Thought I tried that before, but apparently not...

**Comment by ltsNotMike** [comment]
Great to hear that! 🎉 Closing the issue.
