### ISSUE TITLE
Can't add multiple navigation container

### ISSUE THREAD

**Issue by maximeMD** [VirtusLab-Open-Source/strapi-plugin-navigation#210]
Hi there ! 

I don't know if it's just me or if there is currently no possibility to create another Navigation container like the docs seems to put in the Features section.
It also seems that this feature is implemented in plugin-navigation v2.
https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/142

![image](https://user-images.githubusercontent.com/25101871/166825946-abcf273f-33c1-4cdc-92ee-b81740bacc3b.png)

Thanks in advance !

**Comment by cyp3rius** [comment]
Hello @maximeMD ,

We don't have a dedicated form to create navigations :) It will come soon.

As for now you should use the `Content Manager -> Navigations` to create multiple instances.

**Comment by maximeMD** [comment]
Thanks for your help, I didn't think to check in the Content Manager 😄 

I just made a PR for doc, feel free to take it or not !
