### ISSUE TITLE
Make URL field not mandatory/automatic/hidden when using internal source

### ISSUE THREAD

**Issue by mrchristophy** [VirtusLab-Open-Source/strapi-plugin-navigation#212]
When I'm referencing content in a menu item I get the url from the slug field in the attached entity type, making the url field redundant. How can I disable this?

If I'm allowed, can I ask a few other questions:

1 - What does "attach to menu" do? All I can see is that it sets the menuAttached variables in the response.
2 - Am I able to add custom fields to menu items?

Thanks, and sorry if I've broken the rules!

**Comment by ltsNotMike** [comment]
0. Unfortunately, there is no way of disabling the URL field. This feature is being discussed [here](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/152), any updates on this topic will be posted there. 
1. Attach to the menu is a flag that you can use when consuming navigation. You can read more about it [here](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/80). 
2. More advanced custom fields are WIP. At the moment you can only use the audience field to customize your navigation items.

**Comment by ltsNotMike** [comment]
Closing due to no response. Please reopen if needed.
