### ISSUE TITLE
Cannot save external source: Cannot read properties of undefined (reading '__collectionUid')

### ISSUE THREAD

**Issue by sapkra** [VirtusLab-Open-Source/strapi-plugin-navigation#223]
Using the latest beta the frontend crashes if I'm trying to save an external source or wrapper element.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/8087568/172269958-e159f732-32a0-4c9d-80be-0507eb87339f.png">

<img width="619" alt="image" src="https://user-images.githubusercontent.com/8087568/172270052-cf162951-c2ad-4f21-bf7e-8b9e809e8717.png">

**Comment by ltsNotMike** [comment]
Hello @sapkra,

Can you confirm if the issue still persists? It was fixed before releasing from the beta so it should not appear in versions >= 2.1.0
