### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by konhi** [VirtusLab-Open-Source/strapi-plugin-navigation#225]
I'm using this plugin in [my project](https://github.com/ElektronPlus/school-website), and I love it! It has a really simple and pretty interface for creating navigations - I couldn't imagine creating nested navigations without it. It's a must-have for every flexible Strapi-based website.

**Is there any possibility to add custom fields for items?**
- If so, how to do it?
- If not, what should I do in case of need of icons for a specific link?

**Comment by cyp3rius** [comment]
Released as part of `v2.2.0`
