### ISSUE TITLE
Forbidden with Authorization header

### ISSUE THREAD

**Issue by SimoneCarnio** [VirtusLab-Open-Source/strapi-plugin-navigation#227]
I cannot access navigation when i pass the Authorization header.
I've tried to enable the render permission to the Authenticated role but it doesn't work.

I'm missing something or it's a bug?

```
curl "http://localhost:1337/api/navigation/render/albero?type=tree" \
     -H 'Authorization: Bearer *************'
```

```
{
  "data": null,
  "error": {
    "status": 403,
    "name": "ForbiddenError",
    "message": "Forbidden",
    "details": {}
  }
}
```

**Comment by chioio** [comment]
### Env

* @starpi/strapi v4.1.12
* starpi-navigation-plugin v2.1.0

### Permission in public

<img width="617" alt="image" src="https://user-images.githubusercontent.com/36913769/174439462-9bb18fe9-1e45-4699-bbd6-c0d5a94522cf.png">

### Error
```json
{
    "data": null,
    "error": {
        "status": 403,
        "name": "ForbiddenError",
        "message": "Forbidden",
        "details": {}
    }
}
```

**! When I use the strapi in `v4.2.0`, the roles page can't open, like this issue [plugin-users-permissions gives white screen](https://github.com/strapi/strapi/issues/12384https://github.com/strapi/strapi/issues/12384).**

**Comment by chioio** [comment]
I think you can enable permission for public, and try to get by public, and then find the problem in auth permission.

**Comment by SimoneCarnio** [comment]
> Any luck with checking that on your end @SimoneCarnio ? Also worth to use `type=TREE` in new `2.1.0`

Paused the project, I'll work on it next week and I'll see. In my use case I can also use the public access also if it's not convenient

**Comment by cyp3rius** [comment]
The Authenticated access is also supported as that is Strapi default (we don't have any logic on top). Worth to verify.

**Comment by SimoneCarnio** [comment]
Updated strapi to 4.2.0 and strapi-plugin-navigation to 2.10 and now:

- public permission works as aspected as before (if I disable render and don't pass Authorization header -> 403 error)

- passing the Authorization header now works always (no more 403 even with the render permission disabled in authenticated role)

**Comment by Epenance** [comment]
Also experiencing this in dev

**Comment by SimoneCarnio** [comment]
I tried right now to create another api token and it works, the previous one still works with other strapi calls but not with call to the navigation endpoint.
(The previous token for what I rember was created before installing the plugin).  
Will do another test later on both dev and production server

**Comment by Epenance** [comment]
I just retested, it seems that with a read only API key i cannot auth, but with a full access its possible, is this intended?

**Comment by krzysiekplesniak** [comment]
Good point =  full access works

**Comment by cyp3rius** [comment]
Closing the issue as per solution above.

**Comment by Epenance** [comment]
@cyp3rius I wouldn't say this is solved as its not possible to fetch the menu without a full access key which is not what you would like to use in production from my understanding.

**Comment by cyp3rius** [comment]
@Epenance plugin implementation doesn't care about type of token provided, so if Strapi and it logic allows access, then it is going to work. I would rather try to raise an issue with their repo and check for the settings solution. As an authors of plugin we're reusing the output of Context, nothing more.

**Comment by Epenance** [comment]
Fair enough, being new to Strapi it just seemed odd and assumed it would be the plugin since its ilogical behaviour.

Have a great weekend.
