### ISSUE TITLE
Fetch multiple navigations

### ISSUE THREAD

**Issue by jozef-drabik** [VirtusLab-Open-Source/strapi-plugin-navigation#241]
This is more like an question. Is it possible to fetch more than 1 navigation menu ? And if it is how ?

Thanks for reply

**Comment by ltsNotMike** [comment]
Hi @jozef-drabik
Unfortunately, it is not possible. I will flag this as a feature request so maybe we will add this to the backlog in the future.

**Comment by CodeVoyager** [comment]
I'm closing this issue due to no answer from poster. Feel free to re-open, please.
