### ISSUE TITLE
Extend translations

### ISSUE THREAD

**Issue by NeekoGta** [VirtusLab-Open-Source/strapi-plugin-navigation#244]
Hi,

I would like to know how to extends / override the translations? (https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/tree/master/admin/src/translations)

Thank you !

**Comment by ltsNotMike** [comment]
Hi @NeekoGta,

If you would like to extend our translations please feel free to open a pull request with your changes ( e.g. [here](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/pull/131/files) ). I don't think there is a good way of overriding them so the best and fastest way is to open PR.

**Comment by NeekoGta** [comment]
Hi @ltsNotMike 

This is what I intend to do but I would like to know how to add / modify before =)

**Comment by ltsNotMike** [comment]
## Adding new locale
Customizing plugin's locale works the same as customizing strapi admin. You need to create a`src/admin/app.js` file with the configuration of your choice. 

eg.
```js
export default {
  config: {
    locales: ["pl"],
    translations: {
      pl: {
        "navigation.plugin.name": "Nawigacja UI",
        "navigation.header.title": "Nawigacja",
        "navigation.header.description": "Zdefiniuj własną nawigację",
        "navigation.header.action.newItem": "Nowy element",
        "navigation.header.action.manage": "Zarządzaj",
        "navigation.header.action.collapseAll": "Zwiń wszyskto",
        "navigation.header.action.expandAll": "Rozwiń wszystko",
        "navigation.submit.cta.cancel": "Anuluj",
        "navigation.submit.cta.save": "Zapisz",
        "navigation.empty": "Twoja nawigaja jest pusta",
        /* and so on... */
      }
    }
  }
}
```
All the keys for the translation map can be found in mentioned [translation file](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/tree/master/admin/src/translations) for our plugin. However, if you're adding translations this way you have to add 'navigation" as a prefix to each key. (just like in the example)

You can also open a pull request with a new file containing this translation map. The file should be named after the locale (eg. `pl.json`) and be placed in the translations folder in our plugin. Remember that adding a file with translations will not trigger strapi to display this locale as an option in the admin panel. You still have to add locales to your `app.js` config file.

## Modifying existing locale
Overriding the existing locale works the same way. You have to add the `app.js` file with the translations you want to override. 

eg.
```js
export default {
  config: {
    en: {
      "navigation.empty": "There are no elements in your navigation",
    }
  }
}
```

If you think that our translations are faulty you can open a pull request with a modified translations file and we will look into it. 

You can find more info about this topic [here](https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#configuration-options).
If you still have any questions about it please feel free to ask.

**Comment by ltsNotMike** [comment]
Closing. Feel free to ask questions or open if needed.
