### ISSUE TITLE
How to define a title containing non-ASCII characters

### ISSUE THREAD

**Issue by tansongchen** [VirtusLab-Open-Source/strapi-plugin-navigation#252]
I would like to define a navigation where the `title` field is automatically pulled from the entity's `title` field, which contains non-ASCII characters. However when I tried to do this, clicking "Save" gives no response. Any ideas?

**Comment by ltsNotMike** [comment]
Hello @tansongchen,

Could you please provide your strapi, node, and plugin version? 
Also could please check if there are any errors on the browser console or the strapi console? 
This info will help me in investigating this issue.

**Comment by tansongchen** [comment]
I am using Node v16.16.0, Strapi 4.2.3, MySQL 8.0.29 and plugin 2.1.0. Unfortunately there is no error in strapi console or browser console when I tried to save a navigation item with Chinese title or let the title field to be pulled from the entity. There is simply no response. But maybe you can checkout the code here: https://github.com/viva-la-vita/cms , and here are the steps to reproduce:

1. Run the application with `docker compose up -d`, go to localhost:3000/admin
2. Add an entry of the Articles type, where title is non-ASCII (you can copy this Chinese word "测试" for the title there)
3. Enable the Article type for the Navigation plugin, choosing "title" field to be the name field
4. Add a navigation item and leave the title field blank, fill in some arbitrary url, choose "Content Type" to be Articles and choose "测试" from Entity

**Comment by ltsNotMike** [comment]
Thank you for the info. 

I was able to find out what the issue was. This happens because slugify is unable to parse your non-ASCII characters. We created a fix for this but it requires you to add all non-ASCII characters to your navigation config file (see [docs](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation#properties)). This fix was introduced in version 2.2.0 so be sure you update our plugin version. 

I will close the issue but if you have further questions feel free to ask.

**Comment by tansongchen** [comment]
Thanks for your quick fix. I took a look at the solution but I am afraid it wouldn't be feasible for my case since the slugify plugin you used doesn't support the entire Chinese language (which could use thousands of characters), and I am not able to add a huge table to config files. Things I am thinking is:

1. Is it possible to provide a custom function for slugifying instead of a lookup table? I can use the [pinyin library](https://www.npmjs.com/package/pinyin) which is commonly used to slugify Chinese characters.
2. In my case I don't really need the slug since I can use the path as a slug. Is it possible to disable slugifying?

**Comment by ltsNotMike** [comment]
1. I will mention this to my team because at the moment the only way is to provide the lookup table.
2. This slug is used "under the hood". That is why if you add any ASCII character to your title it will save and display all (even non-ASCII) characters.

**Comment by tansongchen** [comment]
I tried adding a in-file look up table as a workaround (see https://github.com/viva-la-vita/cms/blob/f972de50b81e72d663a6aa27452cae67d8f22837/config/plugins.js#L1 ), a little awkward but working fine on my side. Feel free to let me know if there are any better solutions!

**Comment by CodeVoyager** [comment]
Hi @tansongchen,

We want to try another approach. It should give you space to handle your issue in more general way. And with use tools of your liking. More details at https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/pull/262.

**Comment by tansongchen** [comment]
@CodeVoyager Looks good to me! Will give a try once it get merged.
