### ISSUE TITLE
Audience disappears from items when expanding/collapsing them and saving

### ISSUE THREAD

**Issue by kzrodrigo** [VirtusLab-Open-Source/strapi-plugin-navigation#257]
Whenever I expand/collapse an item the save button gets enabled, and if I save, the item looses all set audiences.
This happens both in internal and wrapper items.

![H12bYplSFQ](https://user-images.githubusercontent.com/48213510/181821999-89b759da-22a1-4cbd-af2c-6735e1f45b96.gif)

**Comment by cyp3rius** [comment]
Fixed in version `2.2.1`.

**Comment by daveduya011** [comment]
Issue persists on latest version (2.2.11)
