### ISSUE TITLE
Can't select Slug field as the Path Default field

### ISSUE THREAD

**Issue by matthewbecker1990** [VirtusLab-Open-Source/strapi-plugin-navigation#258]
![image](https://user-images.githubusercontent.com/6112221/182057892-3b8bf31b-0bcc-4911-8e77-38e69694ce71.png)
![image](https://user-images.githubusercontent.com/6112221/182057971-a576cc16-6999-4727-9d52-6d9e9eaf82ae.png)

**Comment by cyp3rius** [comment]
Fixed in version `2.2.1`.
