### ISSUE TITLE
How can I render all the items from a particular Content-Type?

### ISSUE THREAD

**Issue by mcnaveen** [VirtusLab-Open-Source/strapi-plugin-navigation#264]
Can I render all the items from a particular content type as a drop-down menu?

Right now I can choose only one entity. How can I make it display all?

![image](https://user-images.githubusercontent.com/8493007/183425643-fe66ce98-dcfa-4c64-a71a-108bb7b25893.png)

**Comment by ltsNotMike** [comment]
Hello @mcnaveen 
Unfortunately, there is no possibility of attaching more than one entity to the same navigation item.

**Comment by mcnaveen** [comment]
Oh. Let me find another way. Thank you.
