### ISSUE TITLE
Rest api

### ISSUE THREAD

**Issue by danielegustoids** [VirtusLab-Open-Source/strapi-plugin-navigation#273]
Hello! it seems that a token with "read-only" permissions is not enough to consume the rest /api/navigation/render/2?type=tree
it is needed a full access token, using it via GET my expectation would be to use a read-only token.

**Comment by jimmyjamieson** [comment]
I'm getting this issue as well. Works if i directly go in the browser, but calling the API front front-end causes an internal server error. Added the public permissions, but nada

**Comment by cyp3rius** [comment]
We will verify that why default Strapi auth model doesn't allow to access plugin endpoints.

**Comment by cyp3rius** [comment]
So, based on Strapi documentation the "Read-Only" token is dedicated ONLY for Content Manager APIs `find` and `findAll`.  There are two more token types like "Full Access" and "Custom". First one is going to work as name describes but it's not what you expect. By using second one and selecting the plugin endpoints it works as well and you can make it as Read-Only + Navigation.

There is no possibility to enable Read-Only for the custom plugins.

See reference: https://docs.strapi.io/dev-docs/configurations/api-tokens#usage
