### ISSUE TITLE
Custom Fields not working

### ISSUE THREAD

**Issue by mmange** [VirtusLab-Open-Source/strapi-plugin-navigation#275]
Hello, 

Thanks for making and sharing this plugin. I am trying to add some custom fields to the menu but, they are not working or showing up.

I have added  a custom field for eg.

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/314863/188788553-2254e7fe-a28c-4bbd-83f4-ce4c63a74fcf.png">

When I edit any navigation item - I don't see the custom fields

<img width="814" alt="image" src="https://user-images.githubusercontent.com/314863/188788630-be209d05-87db-4e14-9116-6abd8141558e.png">

I am using this plugin on Strapi v4.3.6

**Comment by ltsNotMike** [comment]
Hello @mmange, 

Each custom field can be enabled and disabled in the settings. Please make sure you have enabled the custom fields you want to use. Meanwhile, I will add a fix so that all custom fields are enabled by default.

**Comment by mmange** [comment]
@ltsNotMike - duh..My bad! I guess I missed that small enabled/disabled icon. Thanks for the quick response, I am able to see the custom fields now.
