### ISSUE TITLE
Default path not working with Single Types

### ISSUE THREAD

**Issue by pattenp** [VirtusLab-Open-Source/strapi-plugin-navigation#277]
Hello,

I tried to create navigation with items related to single types. In the settings screen, I selected a field in the single type to use as the default path. When saving navigation item path gets set to undefined.

### Screenshots
![image](https://user-images.githubusercontent.com/5407221/189118196-a9cad59a-97e1-4cd5-90fa-f771edd6a3c6.png)
![image](https://user-images.githubusercontent.com/5407221/189119037-995479e9-48ba-4dbd-b2a2-49320841d877.png)
![image](https://user-images.githubusercontent.com/5407221/189120772-9a1ddad6-4172-4e9e-81b6-714eb2185a38.png)
![image](https://user-images.githubusercontent.com/5407221/189121369-ae3f6ed1-5812-4632-8fc9-5a50ba82eb6a.png)

### Steps to reproduce
1. Create a new project and install the plugin.
2. Create a Single Type named Contact with a field slug. ( See the first screenshot)
3. Go to the settings screen, enable navigation for the single type, and set the slug field as default for the path. (See the second screenshot)
4. Add a new item to navigation, leave the URL field empty, select Contact as content-type, and save. ( See the third screenshot)

### Expected Result 
URL in the contact item should be /contact is undefined. ( See the fourth screenshot)

Thanks for creating this plugin and have a nice day!

**Comment by cyp3rius** [comment]
Released as part of version `2.2.2`.
