### ISSUE TITLE
Ability to create a internal link without related Entity

### ISSUE THREAD

**Issue by tranlehaiquan** [VirtusLab-Open-Source/strapi-plugin-navigation#278]
Hi Navigation's author,
Use case: I have a page name News, it will list all news and It's don't have related entity just need url /news.
Do you think this possible?

**Comment by ltsNotMike** [comment]
Hi @tranlehaiquan,
Have you tried using wrapper elements? I think they will help you with reaching the goal of your use case.

**Comment by tranlehaiquan** [comment]
HI @ltsNotMike 
Got it, thank you.
