### ISSUE TITLE
Save button remains inactive after editing navigation config

### ISSUE THREAD

**Issue by nimame** [VirtusLab-Open-Source/strapi-plugin-navigation#283]
I was able to create my navigation structure in the UI Navigation tab that this plugin adds to Strapi admin. However, when I make changes to my navigation (adding new navigation items or changing existing ones) the "Save" button remains inactive, so I cannot save my changes.

Plugin version: 2.2.1
Strapi version: 4.3.8

**Comment by cyp3rius** [comment]
@nimame We recommend to use version`2.2.2` where this issue being fixed.

**Comment by nimame** [comment]
Thank you @cyp3rius. I upgraded to `2.2.2` but still get the same behavior. Now I also get a warning message when navigating to the "UI Navigation" tab: "Warning: Relations provided in some items are incorrect". I don't know in what way relations are incorrect. Any other suggestions?

**Comment by ltsNotMike** [comment]
@nimame Do you have any internal items in your navigation? If so check if every item has a proper related field provided. This error is displayed when for some reason one of the navigation items doesn't have a related field but should have one. If this isn't the case in your navigation I will investigate further this behaviour.

**Comment by nimame** [comment]
@ltsNotMike yes all navigation items where "Navigation item type" is "internal source" have a content-type and entity selected. I can't find anything looking suspicious. Your help is much appreciated.
