### ISSUE TITLE
What's the difference between this plugin and strapi-plugin-menus?

### ISSUE THREAD

**Issue by boazpoolman** [VirtusLab-Open-Source/strapi-plugin-navigation#284]
Not sure if this is the right place to ask.
But I was wondering what is the difference between this plugin and the [strapi-plugin-menus](https://github.com/mattmilburn/strapi-plugin-menus)?

**Comment by tranlehaiquan** [comment]
Both plugins give us the same feature but, Strapi-plugin-menus is different. You can use it an feel it youself.

**Comment by ltsNotMike** [comment]
Hello @boazpoolman 
There are a lot of subtle differences but both plugins are high-quality solutions for navigation building.

**Comment by ltsNotMike** [comment]
Closing due to lack of response. Please reopen if needed
