### ISSUE TITLE
Error when parent is not menu attached but has children that are with plugin option cascade disabled 

### ISSUE THREAD

**Issue by skyclb** [VirtusLab-Open-Source/strapi-plugin-navigation#285]
Found a bug in the plugin option `Cascade menu attached` when `enabled`. It does not occure when a parent item is not menu attached but its childrens are. Only if you add another level of childrens to the menu attached children like in the below case, the error appears.

Example
- Parent (menuAttached: false)
  - Children (menuAttached: true)
    - Another Children (menuAttached: false)

```
Error: Item not found
at getNestedOrders (node_modules/strapi-plugin-navigation/server/services/client.js:268:35)
at getNestedOrders (node_modules/strapi-plugin-navigation/server/services/client.js:271:31)
at node_modules/strapi-plugin-navigation/server/services/client.js:285:77
at Array.sort (<anonymous>)
at Object.renderType (node_modules/strapi-plugin-navigation/server/services/client.js:285:26)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Object.render (node_modules/strapi-plugin-navigation/server/services/client.js:20:16)
```

Error is thrown in `server/services/client.ts:L360`.

```js
if (isNil(item))
  throw new Error("Item not found");
```

Pull Request: https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/pull/286

**Comment by cyp3rius** [comment]
@skyclb I'm testing this on version `2.3.0-beta.0` and not seeing such issue. I've provided multiple variations of settings for the structure you provided. For all, error does not occur. May I ask you to test that?

**Comment by skyclb** [comment]
Hi @cyp3rius, thanks that you tried to reproduce my error. Thats weird that you don't get the error when reproducing with described options. Unfortunately I can not test it now, because of a client project which I have to work on first. Once this is done, i will test again.

**Comment by cyp3rius** [comment]
Re-open after testing please.
