### ISSUE TITLE
How to call the api from Strapi? (strapi.db.query or strapi.entityService)

### ISSUE THREAD

**Issue by maximelebreton** [VirtusLab-Open-Source/strapi-plugin-navigation#291]
Hello, and thank you for your work on this plugin!

I would like to call the **navigation api** from a **Strapi controller**.

What is the **equivalent** of this public call `http://localhost:1337/api/navigation/render/main-navigation` if I want to call it from a strapi controller?

I suppose it is something like this but I can't find any documentation:
```js
// controller.ts
const response = await strapi.db.query("api::navigation.content-api.render.main-navigation")
```

Thanks!

**Comment by cyp3rius** [comment]
@maximelebreton  that's probably what you're looking for:

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/blob/master/server/controllers/client.ts#L12

You can directly call the service method used in this controller.

**Comment by maximelebreton** [comment]
thanks @cyp3rius, could you provide a little example?

**Comment by cyp3rius** [comment]
like that:

`strapi.plugin('navigation').service('client').render('main-navigation')`

**Comment by maximelebreton** [comment]
Thanks @cyp3rius, but I tried `await strapi.plugin('navigation').service('client').render('main-navigation')  `, and I have a `"NotFoundError: Entity not found"`...

(and the "main-navigation" entity exist because I have data when I call `http://localhost:1337/api/navigation/render/main-navigation`)

**Comment by maximelebreton** [comment]
@cyp3rius ok it's working with: 
```js
await strapi.plugin("navigation").service("client").render({ idOrSlug: "main-navigation" });
```

**Comment by maximelebreton** [comment]
thanks a lot for your time @cyp3rius!
