### ISSUE TITLE
Not able to install on node 18 ( strapi-v4)

### ISSUE THREAD

**Issue by amjadniazi48** [VirtusLab-Open-Source/strapi-plugin-navigation#292]
Plugin is not installing  on the newer version 18

**Comment by amjadniazi48** [comment]
18.12.1

**Comment by CodeVoyager** [comment]
@amjadniazi48 Can you share error message you're facing?

**Comment by amjadniazi48** [comment]
![screenfornavigation](https://user-images.githubusercontent.com/2420029/208091344-aa2b22f9-734f-4407-81b4-b5d255fa27af.png)

**Comment by cyp3rius** [comment]
Fixed in `2.2.3`
