### ISSUE TITLE
After upgrade to Strapi v4.5.4: "Uncaught TypeError: g.indexOf is not a function"

### ISSUE THREAD

**Issue by maxbraeutigam** [VirtusLab-Open-Source/strapi-plugin-navigation#295]
Hello, after upgrade to Strapi v4.5.4 I realised a strange bug on the client side when opening the navigation plugin.
### 0 Start on dashboard
http://localhost:1337/admin/
![image](https://user-images.githubusercontent.com/78037966/208055075-5eee2808-2050-471d-9fee-707310f97a55.png)
### 1 Go to Content Manager
http://localhost:1337/admin/content-manager/
![image](https://user-images.githubusercontent.com/78037966/208055343-6f19ee4e-3eda-4f62-ba68-32e095c5854d.png)
### 2 Go to Navigation Plugin
http://localhost:1337/admin/plugins/navigation
![image](https://user-images.githubusercontent.com/78037966/208055535-c54f06c7-45a5-4164-8f3f-c166c708c0f5.png)
### 3 Create an entry
![image](https://user-images.githubusercontent.com/78037966/208055653-17945b04-4dd1-43ae-8871-c53bc1538e58.png)
### 4 On click on Content Type the error occurs
![image](https://user-images.githubusercontent.com/78037966/208055884-9a4fa0fc-5e5f-44e5-b0dd-8ffe5c6d288a.png)
### Further notes
Step 1 is important to reproduce the error. I can perfectly use the navigation plugin, if I am entering the plugins side directly or refresh the page. Unfortunately, I have no idea of how to further debug the error.
## Config
My `package.json`
```json
{
  "name": "cms",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@strapi/plugin-graphql": "^4.5.4",
    "@strapi/plugin-i18n": "^4.5.4",
    "@strapi/plugin-users-permissions": "^4.5.4",
    "@strapi/provider-email-nodemailer": "^4.5.4",
    "@strapi/provider-upload-aws-s3": "^4.5.4",
    "@strapi/strapi": "^4.5.4",
    "better-sqlite3": "^8.0.1",
    "pg": "^8.8.0",
    "pg-connection-string": "^2.5.0",
    "strapi-plugin-navigation": "^2.2.2",
    "strapi-plugin-publisher": "^1.1.4"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "3bc2bb22-bb12-4e14-90c5-5ce6b886dbc2"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```
## Starting dev
```sh
nvm use lts/gallium
yarn install
yarn build
yarn develop
```

**Comment by cyp3rius** [comment]
Thanks for reporting @maxbraeutigam , we will take a look on this edge case.

**Comment by maxbraeutigam** [comment]
Hi @cyp3rius – I have to apologize for filing this issue since I was able to fix it and—tada—it was my fault.
I solved the problem by moving towards fixed versions in `package.json` (see below) and deleting `yarn.lock` (basically following the [Strapi upgrade guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/update-version.html#step-1-upgrade-the-dependencies)).

Again, I am sorry. Thank you very much for this brilliant plugin, that makes Strapi unique.

Cheers,
Max

```diff
diff --git a/package.json b/package.json
index b38877f..111442a 100644
--- a/package.json
+++ b/package.json
@@ -12,12 +12,12 @@
   "devDependencies": {},
   "dependencies": {
     "@_sh/strapi-plugin-ckeditor": "^1.1.2",
-    "@strapi/plugin-graphql": "^4.5.4",
-    "@strapi/plugin-i18n": "^4.5.4",
-    "@strapi/plugin-users-permissions": "^4.5.4",
-    "@strapi/provider-email-nodemailer": "^4.5.4",
-    "@strapi/provider-upload-aws-s3": "^4.5.4",
-    "@strapi/strapi": "^4.5.4",
+    "@strapi/plugin-graphql": "4.5.4",
+    "@strapi/plugin-i18n": "4.5.4",
+    "@strapi/plugin-users-permissions": "4.5.4",
+    "@strapi/provider-email-nodemailer": "4.5.4",
+    "@strapi/provider-upload-aws-s3": "4.5.4",
+    "@strapi/strapi": "4.5.4",
     "better-sqlite3": "^8.0.1",
     "pg": "^8.8.0",
     "pg-connection-string": "^2.5.0",
```
