### ISSUE TITLE
Caching Problem

### ISSUE THREAD

**Issue by Johannes-Schiel** [VirtusLab-Open-Source/strapi-plugin-navigation#296]
Hello, i have a little problem i use a redis db for caching this works fine with every dataset, but the navigation data is ignored or i do  something wrong. Has some else the same problem or a solution how we can cache the navigations?

"strapi-plugin-redis": "^1.0.1",
"strapi-plugin-rest-cache": "^4.2.5",
"strapi-provider-rest-cache-redis": "^4.2.5"

```javascript
...
"rest-cache": {
  config: {
    strategy: {
        contentTypes: [
            ....
            "plugin::navigation.navigation"
        ]
    }
  }
}
...

```

**Comment by cyp3rius** [comment]
@Johannes-Schiel I would advice you to discuss the topic with developers of [rest-cache](https://github.com/strapi-community/strapi-plugin-rest-cache/issues) plugin. As far as I seen they don't have nothing specific described for Content Types from plugins.

**Comment by Johannes-Schiel** [comment]
Its fine, was an user error by me :D works as expected :)

**Comment by jomarmontuya** [comment]
@Johannes-Schiel  just wondering how do you solve your caching problem using this and rest-cache?  I just happen to bump into the same problem
