### ISSUE TITLE
Plugin causes error with Strapi Enumeration field

### ISSUE THREAD

**Issue by GamendeBrian** [VirtusLab-Open-Source/strapi-plugin-navigation#298]
I'm using version 4.5.5 of Strapi (also tried 4.5.6 that released yesterday, also didn't work).

When trying to click open an Enumeration field, either in a Dynamic Zone or individually, it gives a white screen with the following console error(s):

`main.8e54019d.js:10003 
Uncaught TypeError: g.indexOf is not a function
    at Da (35.cc19d1fb.chunk.js:1:503)
    at Y (main.8e54019d.js:12187:34253)
    at main.8e54019d.js:8:26204
    at Object.X [as current] (main.8e54019d.js:12187:34028)
    at main.8e54019d.js:8:26607
    at qc (main.8e54019d.js:10005:1455)
    at dn (main.8e54019d.js:10007:5413)
    at r.unstable_runWithPriority (main.8e54019d.js:10035:3935)
    at Ho (main.8e54019d.js:10003:39415)
    at un (main.8e54019d.js:10007:1882)`

See also screenshots here:

<img width="436" alt="strapi-navigation-issue-console" src="https://user-images.githubusercontent.com/39622911/212108553-50d6bfb6-4154-4241-b157-895b1dccad87.png">

<img width="463" alt="strapi-navigation-issue-strapi" src="https://user-images.githubusercontent.com/39622911/212108563-b40a5a61-be0c-4d50-aa6e-78fe1e921115.png">

I have also tried this with a fresh install. It worked.
Then tried adding the plugin. It gave the error.

Did anyone already encounter this or..?

**Comment by friconelli** [comment]
same here!

**Comment by cyp3rius** [comment]
Checking.

**Comment by GamendeBrian** [comment]
Hi @CodeVoyager,

Thank you for your response and effort to reproduce.

I'm not sure in what step it went wrong, but somehow we found a way to use `npx strapi build && npx strapi develop` (instead of `yarn build && yarn develop` and that made the white pages not show up at all anymore.

Besides that, all possible white error pages have turned into a Strapi error page instead.
I couldn't have reproduced the issue again since then.
