### ISSUE TITLE
[FE BUG] - Overflow-x hidden makes edit and remove button unavailable to click

### ISSUE THREAD

**Issue by everythinginjs** [VirtusLab-Open-Source/strapi-plugin-navigation#299]
Hello guys, there is an issue when the url is in another language (Farsi) since it is converted to `encodeURI('به عنوان مثال')`, so it gets something like `'%D8%A8%D9%87%20%D8%B9%D9%86%D9%88%D8%A7%D9%86%20%D9%85%D8%AB%D8%A7%D9%84'` would be appreciate to truncate or x-scroll so the buttons get reachable I attached an image of the bug.
Thanks 🙏 
<img width="1018" alt="Screenshot 2023-01-12 at 7 16 32 PM" src="https://user-images.githubusercontent.com/34276557/212113500-e2f98d82-61a5-49f0-899a-13d5de289d7b.png">

**Comment by cyp3rius** [comment]
Fixed in `v2.2.4`
