### ISSUE TITLE
How can I export the current navigations items?

### ISSUE THREAD

**Issue by gustavos00** [VirtusLab-Open-Source/strapi-plugin-navigation#301]
Hello,

I want to export my current settings for the navigation items and their structure as well. Is possible to directly export them or use any plugin for this?

**Comment by cyp3rius** [comment]
@gustavos00 as for now we don't have dedicated Export / Import feature built in the plugin. What I can suggest you is use of this: https://market.strapi.io/plugins/strapi-plugin-import-export-entries 

Note: We didn't test that, it just a guess this plugin might be useful.

**Comment by gustavos00** [comment]
Hello @cyp3rius. 

I really appreciate your fast answer but I guess this plugin will not work. Currently, the navigation plugin doesn't create the content types directly. There is any other idea? I have been trying to find a solution but at least right now, I don't have anything.

**Comment by cyp3rius** [comment]
There are contrnt types in reality but hidden for Content Manager in Strapi. I'll think on the options for more perm solution. 

As an idea you might try to modify the plugin content type settings by an extension and allow them to be present in Content Manager.

**Comment by cyp3rius** [comment]
Discussion is going to be continued as part of #317
