### ISSUE TITLE
Same Entity in a different menu item 

### ISSUE THREAD

**Issue by luisjorp** [VirtusLab-Open-Source/strapi-plugin-navigation#307]
I'm required to include the same page entity in two different menu items of the same menu (due to a client request). However, if it has already been added, I am unable to add it a second time.

I'm running Strapi 3.6.8 and this plugin's version 1.0.4.

**Comment by cyp3rius** [comment]
Hello @luisjorp in v3 it's not possible. In v4 you can manage it by Wrappers and or External items linking to the paths generated by Internal Items. 

You can try to provide External link to the path generated for your Internal item as well in v3, but I can't guarantee it's going to work.

As per Strapi we're no longer supporting any feature requests for v3. Please update to v4 to get the proper level of support. Thanks.
