### ISSUE TITLE
The model pages can't be found.

### ISSUE THREAD

**Issue by luisjorp** [VirtusLab-Open-Source/strapi-plugin-navigation#308]
I upgraded from the 1.0.4 to 1.1.4 version because I'm using Strapi 3.6.8 and when I try to run the yarn develop command I get this error
<img width="1364" alt="Screen Shot 2023-02-16 at 12 02 59 PM" src="https://user-images.githubusercontent.com/6946476/219450223-952a5286-66df-422b-b285-7359b160a4e0.png">

Any suggestion on what I'm missing or how to fix this?

**Comment by luisjorp** [comment]
<img width="283" alt="Screen Shot 2023-02-16 at 12 07 56 PM" src="https://user-images.githubusercontent.com/6946476/219451278-160747ba-b89c-426a-9b8e-6750d011ae90.png">

**Comment by cyp3rius** [comment]
Closing because lack of response.
