### ISSUE TITLE
Cannot read properties of undefined (reading 'content-manager')

### ISSUE THREAD

**Issue by skouzzi** [VirtusLab-Open-Source/strapi-plugin-navigation#309]
# Bug Report
Cannot enter navigation plugin configuration or Navigation UI after editing content-types which should be enabled for navigation on the navigation plugin configuration.

## Steps to Reproduce

1. Upgraded strapi to version 4.6.0 and all relevant dependencies
2. changed some content-types which should be enabled for navigation
3. trying to enter navigation plugin configuration or Navigation UI again

## Other Details

![Bildschirm­foto-2023-02-17-um-10 18 16](https://user-images.githubusercontent.com/107535112/219606381-c6745b92-4e1d-4914-b419-611a350cf55b.jpg)

**Comment by cyp3rius** [comment]
Cannot reproduce. Can you please check if occur with version `2.2.5`?

**Comment by skouzzi** [comment]
I just did another research round and recognized, that one of the selected collectionTypes in the navigation plugin configuration was missing the "pluginOptions" in the schema. Now after adding it, the plugin works again as intended.
