### ISSUE TITLE
Wrong redirection on menu item related page

### ISSUE THREAD

**Issue by ToonMolo** [VirtusLab-Open-Source/strapi-plugin-navigation#312]
In my case, I have several translated menus.

On menus other than the default locale, when you click on the page associated with a menu item, you are redirected to the correct page but the locale is always the default locale, and not the locale of the page clicked (in my case, it should be FR).

Here is an example video :

https://user-images.githubusercontent.com/8549974/224767915-d092e1ab-4470-4ee5-8840-86fda42d86dd.mov

**Comment by cyp3rius** [comment]
Fixed in `v2.2.7`
