### ISSUE TITLE
Cannot not set navigation item in Chinese

### ISSUE THREAD

**Issue by soapwong703** [VirtusLab-Open-Source/strapi-plugin-navigation#314]
When createing an navigation item with chinese title, it cannot be saved.  Seems the query getting the slug (http://localhost:1337/navigation/slug?q=%E4%BD%A0%E5%A5%BD) returned empty string and blocked the creation.

![image](https://user-images.githubusercontent.com/68498079/225604751-c364bbb1-1116-4829-b500-57e1bfa8db17.png)

**Comment by cyp3rius** [comment]
@soapwong703 you've to follow the [documentation](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation#properties) and extend the `slugify` and support Chineese.

**Comment by soapwong703** [comment]
> Note for newer than v2.2.0 slugify as been removed. THIS A BREAKING CHANGE

@cyp3rius I see the documents says slugify has been removed, and I have tried to write a function on slugify which doesn't work too.
```
navigation: {
    enabled: true,
    config: {
      i18nEnabled: true,
      slugify: () => "Test",
    }
}
```

**Comment by cyp3rius** [comment]
I see that documentation is outdated, and by some reason the part with `slug` generation is not attached.

See: https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/pull/262/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R631

I'm going to fix the doc in upcoming release.

**Comment by soapwong703** [comment]
I can extend the slugify service now, thanks!
