### ISSUE TITLE
Permission settings are not applied

### ISSUE THREAD

**Issue by manu7823** [VirtusLab-Open-Source/strapi-plugin-navigation#315]
If I create a new custom role and give it read-only navigation permissions, a user with that role can still update navigation items.

<img width="2548" alt="Bildschirm­foto 2023-03-28 um 14 17 26" src="https://user-images.githubusercontent.com/53856345/228233433-ca80c637-a579-47cd-b120-2187bbb410a4.png">

<img width="1563" alt="Bildschirm­foto 2023-03-28 um 14 20 17" src="https://user-images.githubusercontent.com/53856345/228234056-f4da02e2-a60c-4251-9914-f5357f3f8ced.png">

Setup: 
"dependencies": {
    "@strapi/plugin-i18n": "4.8.2",
    "@strapi/plugin-users-permissions": "4.8.2",
    "@strapi/strapi": "4.8.2",
    "better-sqlite3": "8.0.1",
    "strapi-plugin-navigation": "^2.2.4"
  }

Please check the permission's functionality in general. That's not the only thing which is broken. Restricting "Read" and "Update" permissions to "Is Creator" or "Has same role as creator" also doesn't work. 

Also, it would make sense to me to have an additional option to give read and update permissions to the navigation settings page separately.

**Comment by soapwong703** [comment]
Having the same issue, both Read and Update permission is not working.  This is a major security risk, any target fix time? @cyp3rius

**Comment by cyp3rius** [comment]
In progress already. Expecting 1-2 days.

**Comment by cyp3rius** [comment]
Version `2.2.5` contain this fix.

**Comment by soapwong703** [comment]
@cyp3rius Thanks for the update! I can see the admin panels is blocked with permission, however when I using the api to get and updates the navigations it still disregard on the permission and succeed.  Would you also kindly block this?

**Comment by cyp3rius** [comment]
@soapwong703 so you are using admin endpoints directly as well? Not only public API?

**Comment by soapwong703** [comment]
@cyp3rius Yes we are having security test and found that the plugin's admin apis doesn't block with permissions.

**Comment by cyp3rius** [comment]
So for this you are using the admin user tokens, am I right? Is this issue common across Strapi or just Navigation plugin got it?

**Comment by soapwong703** [comment]
Strapi's own api has permission checking and will return error when don't have the correct permissions.  You can check more on https://docs.strapi.io/dev-docs/api/plugins/server-api#policies

<img width="905" alt="螢幕截圖 2023-04-06 下午1 20 44" src="https://user-images.githubusercontent.com/68498079/230278872-d9f53a6e-2503-46a8-9088-c1c7029a9313.png">

**Comment by cyp3rius** [comment]
Ok so seems the previous solution we got for this is not proper anymore :) will dig into the Strapi common and take it as separated issue. Any ETA you must have it fixed?

**Comment by soapwong703** [comment]
@cyp3rius Wishing to fix it by this weekend.  You can easily add policy to check permission with:

```
server/routes/admin.js
{
    method: 'GET',
    path: '/',
    handler: 'admin.get',
    config: {
        policies: [{
            name: "admin::hasPermissions",
            config: {
                actions: ["plugin::navigation.read"],
            },
        }]
    }
},
```

**Comment by cyp3rius** [comment]
Yep, Thats what I'm doing now. Should be done by EOD today.

**Comment by cyp3rius** [comment]
@soapwong703 version `2.2.6` contains policy check. All should be secured as for now.

**Comment by manu7823** [comment]
@cyp3rius Thank you very much for fixing the general read and update permissions. The second point I mentioned: `Restricting "Read" and "Update" permissions to "Is Creator" or "Has same role as creator" also doesn't work.` is still there. I added a new issue #330
