### ISSUE TITLE
populate=* returns sensitive information

### ISSUE THREAD

**Issue by mike85** [VirtusLab-Open-Source/strapi-plugin-navigation#316]
When I request the navigation through the following path, the entire user object gets exposed, including hashed passwords:
`api/navigation/render/main-navigation?type=TREE&populate=*`

Is there a setting to hide such fields?

Sample Response:
`"updatedBy": {
            "id": 1,
            "firstname": "",
            "lastname": "",
            "username": null,
            "email": "",
            "password": "$2a$10$l......",
            "resetPasswordToken": null,
            "registrationToken": null,
            "isActive": true,
            "blocked": false,
            "preferedLanguage": "de",
            "createdAt": "",
            "updatedAt": ""
        },`

Strapi Version: 4.8.2
Plugin Version: 2.2.4

**Comment by cyp3rius** [comment]
Fixed in `v2.2.7` for the default attributes like `createdBy` and `updatedBy`. Anyway we recommend to control the populate by the plugin configuration page instead, where you can clearly select fields per each Content Type you would like to populate.
