### ISSUE TITLE
Removing audience from settings, let the content type enabled

### ISSUE THREAD

**Issue by ScreamZ** [VirtusLab-Open-Source/strapi-plugin-navigation#326]
Hi,

Just wanted to enable the audience type for testing as I don't really get what is it for. Now I have an Audience content type, available for edition to my end user, whereas I'm not using it.

What's the safe way to revert this?

**Comment by cyp3rius** [comment]
Hello @ScreamZ,

where you've removed it ? In the file or via the user interface? After initializing, plugin takes values from file and from that point if you would like to get the file properties working you must "Restore" settings via the user interface.

**Comment by cyp3rius** [comment]
Closing because lack of response.
