### ISSUE TITLE
type tree not working

### ISSUE THREAD

**Issue by TasosBak** [VirtusLab-Open-Source/strapi-plugin-navigation#328]
Hello and thank you for this awesome plugin!

I have constructed a menu of the following structure using you plugin:

- wrapperElem1
    - wrapperElem1.1
        - externalSource1.1.1
        - externalSource1.1.2
    - wrapperElem1.2
        - externalSource1.2.1
        - externalSource1.2.2
- wrapperElem2
    - wrapperElem2.1
        - externalSource2.1.1
        - externalSource2.1.2
    - wrapperElem2.2
        - externalSource2.2.1
        - externalSource2.2.2

I am using http://localhost:1337/api/navigation/render/1?type=tree to get the data but the response is the same regardless if I use flat/tree. Did I miss something from the doc?

**Comment by kschutt** [comment]
+1 having a similar issue where the `items` attribute is coming back `null` through the API

**Comment by cyp3rius** [comment]
Try with: `type=TREE` 

This is case sensitive because of service and controller usage by both REST and GraphQL (which types are case sensitive)

As well in [documentation](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation#rest-api) we're using all as uppercase.

**Comment by TasosBak** [comment]
Thanks for the response!

Have also tried with TREE though and not getting different result. Does it matter if they have attach to menu and cascade on? I think I've tried all possible combinations but wasn't able to get it to work.

Also does the type of the item (wrapper, internal, external) affect the children population?

**Comment by TasosBak** [comment]
Leaving the previous comment intact in order to not cause any confusion. I started a new project and added the plugin from scratch and it works with `type=TREE` ! I'll come back if I lose the functionality again! 

Thank you very much for your time!

**Comment by cyp3rius** [comment]
Closing then :)
