### ISSUE TITLE
Lifecycle hook extension

### ISSUE THREAD

**Issue by ijlind** [VirtusLab-Open-Source/strapi-plugin-navigation#332]
I have a use case where I would need to be able to run additional code after a navigation item is created/updated. The logical way to do this would be to use an `afterCreate`/`afterUpdate` lifecycle hook but I've had no luck getting those to work with the plugin. I've tried to manually add the hooks during the register phase or via `extensions/navigation/strapi-server.ts` or `extensions/navigation/content-types/navigation-item/lifecycles.ts` but none of these seems to work.

Is there a way of doing this currently?

This topic was touched upon on #251 but there the end result was apparently that you can extend the schema but not the lifecycle methods.

**Comment by CodeVoyager** [comment]
Hi @ijlind,

There's a PR addressing your request. Have a look please.

**Comment by cyp3rius** [comment]
Released as part of `2.4.0`.
