### ISSUE TITLE
Add image to navigation item

### ISSUE THREAD

**Issue by TasosBak** [VirtusLab-Open-Source/strapi-plugin-navigation#337]
Hey there! 

Is there any chance you could guide me in adding a new "image" custom field? This is for the case that the navigation item has an image/icon associated with it. 

So if you have added a new custom field of type "image" through the plugin's settings, you would see something like that in the Add/Edit element popup. 

<img width="550" alt="image" src="https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/15340410/879f610b-2b63-4d46-8eb2-22424e814cda">

Then in the List view, on the left of each item we could show a preview of the image and lastly, the url of the image will have to be returned with the rest item info.

Any thoughts on how I could go about triggering the media library modal to come up? I believe that the rest won't be a problem. Would be happy to contribute once I implement it of course!

**Comment by CodeVoyager** [comment]
Hi @TasosBak,

There's a PR addressing this story. Have a look, please.

**Comment by cyp3rius** [comment]
Released as part of `2.4.0`.
