### ISSUE TITLE
Is there any way to import/export navigation items

### ISSUE THREAD

**Issue by vjsampas** [VirtusLab-Open-Source/strapi-plugin-navigation#338]
Hi,

We have installed strapi navigation plugin in our environment & created big hierarchy for navigation. Now we want to migrate all content to another environment but seems that navigation hierarchy is not getting exported through import/export plugin.

"strapi-plugin-navigation": "^2.2.3"
"strapi-plugin-import-export-entries": "^1.18.0"
"@strapi/strapi": "4.7.0"

If it's not supported is there any alternative way to import this hierarchy?

**Comment by cyp3rius** [comment]
Hello @vjsampas,

you should use default Strapi import / export functionality but it work only if you migrate to the new database (no previous indexes). See the discussion in #317
