### ISSUE TITLE
Frontend crashed when I added external link using external source

### ISSUE THREAD

**Issue by SSDO-Pakistan** [VirtusLab-Open-Source/strapi-plugin-navigation#339]
Frontend crashed when I added external link using external source with version 2.2.8 with strapi version 4.10.5

**Comment by cyp3rius** [comment]
More details please. Especially the browser console.

**Comment by SSDO-Pakistan** [comment]
Nothing is shown in the console on my next.js webiste, when the  navigation renders everything disappear and nothign shown in the console as well while api with tree shows external link correctly

**Comment by cyp3rius** [comment]
So it's invalid issue raised agains plugin. You've got problem on the client side where you're consuming navigation structure created by Strapi and plugin.

We are not supporting user end as thats the idea of headless. Check your Next.js portal codebase please.
