### ISSUE TITLE
Adding relation to navigation items in another collection

### ISSUE THREAD

**Issue by dmarkbreiter** [VirtusLab-Open-Source/strapi-plugin-navigation#340]
I'm trying to relate a page in a Pages collection to to a navigation item in crated from the navigation plugin. To do so, I added the following code to my Pages collection's schema.json: 
```
    "navigation": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "plugin::navigation.navigation-item"
    }
```
Which allows the user to select nodes from the navigation plugin (see photo)
![Screen Shot 2023-05-21 at 10 14 44 AM](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/58999191/1e03abc3-6d6d-43cb-a284-2c895b6e4503)

The issue is when I query my pages collection, the navigation relation does not show up, even after giving Public users access to the navigation plugin and making sure to use `populate=*`

Ideally, I'd like to be able to relate to nodes in a navigation container and have the pages api return with at least the path of the navigation item. Is this possible?

**Comment by cyp3rius** [comment]
Hello @dmarkbreiter, its not the way how navigation plugin works. Please follow the manual and setup Collections which you want to use via the configuration page and create the structure using built-in editor.
