### ISSUE TITLE
I've updated strapi version and the plugin now doesn't work like before

### ISSUE THREAD

**Issue by diegobaratta** [VirtusLab-Open-Source/strapi-plugin-navigation#341]
As the title says, I was working with this plugin then I've updated my strapi from v4.8 to v4.10. I've ran "yarn" command and "yarn build" too already but the plugin doesn't work like before. I've configured it to take my Content Type's title and slug by default when I didn't write anything on Title and URL fields, but now if I leave'em blank, it claims that I should write something instead of taking the default values.

![imagen](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/3035938/32ce50a7-c5a1-4b27-8a26-46acc8559fde)
![imagen](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/3035938/fad1efe5-09ac-4692-a9e4-71386222cedc)

**Comment by cyp3rius** [comment]
Checking on v4.10

**Comment by diegobaratta** [comment]
Is there some news?

**Comment by cyp3rius** [comment]
I was able to reproduce your case with 2 versions of `4.10.x` (not sure why). Anyway working on the solution.

**Comment by Raesta** [comment]
same problem here, o you have plan for fix this bug

**Comment by cyp3rius** [comment]
You was quicker than me :) Will review your PR tonight and release the version with fix. Thank you for contribution!

**Comment by cyp3rius** [comment]
Version `2.2.9` published with @Raesta fix. Thanks!

**Comment by diegobaratta** [comment]
Hi, thanks for the effort to fix this, it's appreciated. The default slug now works fine, like before, but it doesn't take the default title yet. In fact, if you don't write anything on the title field and hit save, instead of take the default content type's title as configured, nothing happens. Not even an error, it just stays stuck there till you write some title.

**Comment by graphicfox** [comment]
@cyp3rius Same Problem like @diegobaratta has.
