### ISSUE TITLE
Is there a way to add a relation to one of navigations created?

### ISSUE THREAD

**Issue by c3s4** [VirtusLab-Open-Source/strapi-plugin-navigation#349]
Hi,
I was trying to find a way to add a relation to navigation plugin. I mean: imagine you have a single type used as site global configuration where I set many things, the page that is the homepage (using a relation to the page content type), a relation to cookie page and so on.
Using my custom menu content type I had a relation to a menu, so the user could create different menus and select the desired one using that relation.

So the question: is it possible to add a relation to navigations so the user can choose the one he wants?

**Comment by tim-vyg** [comment]
I'd +1 this, for example we'd quite to make our link component be able to refer to the NavigationItem collection so a user could select from a page route that exists

But I see you dismissed https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/340 

We're generating all our routes from the navigation plugin, is there a workaround to make a link component that reads from existing routes?

**Comment by cyp3rius** [comment]
To archive that you can try to extend the Content Types of our plugin using Strapi Extensions strategy and simply do the changes in this part:

```ts
  pluginOptions: {
    "content-manager": {
      visible: false
    },
    "content-type-builder": {
      visible: false
    },
    i18n: {
      localized: false
    }
  },
```

- `content-manager` is responsible for availability of Content Type in the Editor
-  `content-type-builder` is responsible for availability of Content Type in the Builder

Hope it gives you some kind of direction :)

**Comment by cyp3rius** [comment]
Closing as no response.
