### ISSUE TITLE
Related title not parsed

### ISSUE THREAD

**Issue by nezzard** [VirtusLab-Open-Source/strapi-plugin-navigation#350]
The related title is not parsed. I checked the sanitizePayload function, and it seems that the payload.title for related items is always an empty string "". Therefore, the getDefaultTitle function is never triggered.

 "strapi-plugin-navigation": "^2.2.11"
 "@strapi/strapi": "4.11.0",

**Comment by Xromern** [comment]
I might have the same problem. When adding collection-type content, the title is not fetched from the entity, and when I click the save button, nothing happens. However, if I manually enter the title, the saving process is successful.

![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/29869231/5b2ba8a3-0c6b-43bb-ada3-ede3352f2bc7)
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/29869231/156c65d4-a377-479e-bd69-94e40eee9a3d)

**Comment by cyp3rius** [comment]
Planning release for early next week.

**Comment by cyp3rius** [comment]
Fixed in `v2.3.1`
