### ISSUE TITLE
Typescript Types for REST API Response in Client code

### ISSUE THREAD

**Issue by EsGeh** [VirtusLab-Open-Source/strapi-plugin-navigation#352]
### Question

**Is there a npm package that provides the necessary type definitions for the client side?**

To be more precise:
When requesting  the api at `/api/navigation/render/main-navigation` in some client - what typescript type does the returned data have?

### Example

Some client trying to fetch navigation data from a strapi backend via REST:

```
export async function getNavigation()
	// : ???
{
  const response = await fetch( "/api/navigation/render/main-navigation", {} );
  if( ! response?.ok ) {
    throw new Error( `Error when fetching data from '${url}': returned HTTP status '${response.status}'` );
  }
  const data = await response.json();
  if( !data ) {
    throw new Error( `Error when fetching data from '${url}': no data!` );
  }
  return data // as ???
}
```

**Comment by cyp3rius** [comment]
Hello @EsGeh , 

there is no such type yet but good shout! I'm putting this request to backlog.

**Comment by cyp3rius** [comment]
Added in `v2.3.1`
