### ISSUE TITLE
Save button won't work when there is an item with the same path within your navigation

### ISSUE THREAD

**Issue by nicknijenhuis** [VirtusLab-Open-Source/strapi-plugin-navigation#361]
Save button won't work when there is an item with the same path within your menu, in my example I was some levels deep inside the menu, but I think it doesn't matter where you are. 

![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/1682162/cb5f942f-7176-40eb-9e6c-9d83277a2ff8)

Steps to reproduce
1. Add a menu item with an internal source with some path 
2. Save
4. Add another menu item with the same path
5. Save

**Expected: The form gives an error or a warning about that you can't use the same path
Actual: The form does nothing and no feedback is given**

Version:
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/1682162/e3b271c7-d507-4a03-aa21-5d10b969f4dd)

**Comment by CodeVoyager** [comment]
Hi @nicknijenhuis 

A PR covering your issue is in review.

**Comment by cyp3rius** [comment]
Fixed in `v2.2.13`
