### ISSUE TITLE
Audience disappears from items after saving

### ISSUE THREAD

**Issue by daveduya011** [VirtusLab-Open-Source/strapi-plugin-navigation#364]
Selected audience disappears after saving. It was resolved before on #257 , but persists on the latest version (2.2.11) as I was using it.

**Comment by iamandrewluca** [comment]
This seems to be the same issue.

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/384

**Comment by cyp3rius** [comment]
Fixed in `v2.3.1`
