### ISSUE TITLE
Bug when change default language difference than en, fr

### ISSUE THREAD

**Issue by thongbn** [VirtusLab-Open-Source/strapi-plugin-navigation#369]
I got some crash when upgrade strapi from 4.12.1 to 4.13.3, because i change default language from en to vi and got crash in getTrad. See image below. I have to add vi in trads list to make it work
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/14286010/849d8e7a-8bf2-46c3-8037-45a6eb8b1292)

**Comment by artzyres** [comment]
Hi,
We get the same here with our defaults being in German (de) when upgrading from Strapi 4.12.7 to Strapi 4.13.3.
Patching as done by @thongbn (with `de` instead of `vi`) works also for us.

**Comment by cyp3rius** [comment]
Check please the last two versions of plugin, fallback for language was added.

**Comment by cyp3rius** [comment]
Closing because lack of response. Re-Open if still occurs.
