### ISSUE TITLE
How can I get the navigation id ?

### ISSUE THREAD

**Issue by lchhieu** [VirtusLab-Open-Source/strapi-plugin-navigation#370]
In UI, I don't see where to find the id of navigation. 
I'm using the navigation id to work with strapi API 
![Screen Shot 2023-09-07 at 14 57 49](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/11382616/a9568b00-d443-4900-9ac7-fb6d6432579e)

**Comment by CodeVoyager** [comment]
Hi @lchhieu 

There's a PR covering your request. Have a look, please.

**Comment by cyp3rius** [comment]
Provided in version `v2.2.15`
