### ISSUE TITLE
Feature request: make an endpoint that returns all navigations

### ISSUE THREAD

**Issue by fabiennecornel** [VirtusLab-Open-Source/strapi-plugin-navigation#379]
Hello, instead of having to do a request to something like (...)/api/navigation/render/xyz for each navigation, it would be valuable to have 1 endpoint that returns all navigations, each containing at least the id, name, slug, and items.

It exists in the strapi admin panel but not in the API.

So an array of the navigations like this (url: GET strapi url/navigation): 
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/100563015/258d8214-4afb-4044-9ab8-be4a7a921fab)

but every navigation has the items too (url: GET strapi uri/navigation/{id}): 
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/100563015/278a93ec-c05d-4ab8-a9b6-0f8ec09aa2b1)

**Comment by Bryelmo** [comment]
Hi everybody,
I agree with @fabiennecornel, this new feature would be very useful.

@fabiennecornel did you solve creating a custom endpoint on Strapi?

**Comment by cyp3rius** [comment]
We are going to include it in one of next two releases
