### ISSUE TITLE
The bug that closes the modal conflicts with the dropdown menu's closing functionality

### ISSUE THREAD

**Issue by FamManh** [VirtusLab-Open-Source/strapi-plugin-navigation#384]
Hello, thanks for the awesome plugin, 

My create new navigation item modal automatically closes when I click outside of the red box to close the dropdown. I encounter the same issue when trying to select an audience.
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/29099821/0f98682d-8703-449f-a6db-641f5ea92b6a)
Could you help me?

My package.json:
- @strapi/strapi v4.14.2
- strapi-plugin-navigation v^2.2.16

**Comment by cyp3rius** [comment]
Investigating. Please provide your package.json or at least version of Strapi

**Comment by FamManh** [comment]
Thank you for the quick reply. I have updated the issue description.

**Comment by bora89** [comment]
Same for me. If you just check `Navigation item type` select menu - a whole modal will be closed, as well as click outside (which should not be the case when you loose all what you wrote in edits...)

**Comment by bora89** [comment]
Any updates? More that a month passed

**Comment by cyp3rius** [comment]
Fixed in `v2.3.1`
