### ISSUE TITLE
Cannot build plugin locally

### ISSUE THREAD

**Issue by TasosBak** [VirtusLab-Open-Source/strapi-plugin-navigation#386]
Hello all!

I am using the latest version of the plugin (2.2.16) with strapi version 4.14.2.

I added the code of the plugin into my project and have added the following lines in the `config/plugins.js `. 

```
  navigation: {
    enabled: true,
    resolve: "./src/plugins/strapi-plugin-navigation/build",
  },
```

I did that because I have some custom logic that I want to incorporate **after I get the vanilla plugin to work**. (I am not new to the plugin nor to strapi, I have customized this plugin back in version 2.2.8 with strapi version 4.9.2.)

I am navigating into the directory where I've added the code and I am running 
```
npm install 
npm run build
```

and I get the following errors

```
admin/src/components/DragButton/index.tsx:59:33 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: PolymorphicComponentProps<"web", FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, never>, void, void, {}, {}>): Element', gave the following error.
    Type 'ForwardedRef<unknown>' is not assignable to type 'LegacyRef<HTMLSpanElement> | undefined'.
      Type 'MutableRefObject<unknown>' is not assignable to type 'LegacyRef<HTMLSpanElement> | undefined'.
        Type 'MutableRefObject<unknown>' is not assignable to type 'RefObject<HTMLSpanElement>'.
          Types of property 'current' are incompatible.
            Type 'unknown' is not assignable to type 'HTMLSpanElement | null'.     
  Overload 2 of 2, '(props: FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, never>): ReactElement<...>59   <DragButtonWrapper {...props} ref={ref}>
                                   ~~~

  ../../../node_modules/@types/react/index.d.ts:148:9
    148         ref?: LegacyRef<T> | undefined;
                ~~~
    The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & FastOmit<Substitute<FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, never>, FastOmit<...>>, keyof ExecutionProps> & FastOmit<...> & { ...; }'
  ../../../node_modules/@types/react/index.d.ts:148:9
    148         ref?: LegacyRef<T> | undefined;
                ~~~
    The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, never>'


Found 1 error in admin/src/components/DragButton/index.tsx:59
```

Does anyone have any suggestions?

**Comment by TasosBak** [comment]
Hello, do we have any update here? Any suggestions?

**Comment by cyp3rius** [comment]
@TasosBak can you please check the latest version? We've updated Strapi dependency as well there to cover typing issues.

**Comment by robaraujodevops** [comment]
I'm having the same issue with the latest version.

**Comment by cyp3rius** [comment]
Checking then.

**Comment by TasosBak** [comment]
Thanks for getting back to me! 

I recently tried to build the project with NODE_ENV=production and I get many errors regarding the testing files.

**Comment by TasosBak** [comment]
This is not about the comments plugin (haven't had the opportunity to work with that yet :) ), can I use the comments plugin as a reference? 

The errors I mentioned occur on the tsc step. What made you think I'm skipping the transpilation step?

**Comment by TasosBak** [comment]
The errors start with this:
__mocks__/strapi.ts(1,88): error TS2307: Cannot find module 'strapi-typed' or its corresponding type declarations.
admin/src/pages/SettingsPage/types.ts(1,45): error TS2307: Cannot find module 'strapi-typed' or its corresponding type declarations. 

and I only get it when I run it with the NODE_ENV=production

**Comment by TasosBak** [comment]
Just to be clear, the original errors are not fixed, I just get new ones when I run it in with the NODE_ENV=production

**Comment by cyp3rius** [comment]
The `strapi-typed` is in `devDependencies`. Have you done `yarn install` in the directory where you've got cloned `navigation` plugin?

**Comment by TasosBak** [comment]
Yeap of course! The thing is that npm i stopped working after an update and I had to use npm install --legacy-peer-deps. Is that something that could cause an issue?

**Comment by cyp3rius** [comment]
We've moved discussion to Discord. Will drop a note with outcome once solved.

**Comment by cyp3rius** [comment]
The typing errors because of dependencies bumped. As discussed @TasosBak will try to make a contribution with fix.

**Comment by CodeVoyager** [comment]
Hi @TasosBak,

A PR is create to address your issues. Have a look, please.

**Comment by cyp3rius** [comment]
PR was merged. Try to pull the repository again @TasosBak, all should work as expected.

I'm going to release this typings fix in in the upcoming version.
