### ISSUE TITLE
Security issue: populate filter shows user data into the API

### ISSUE THREAD

**Issue by Bryelmo** [VirtusLab-Open-Source/strapi-plugin-navigation#401]
Hi everybody,

I think I found a security issue using populate params into the API endpoint.

`/api/navigation/render/:id?populate=*`

If I have an attached page to the menu item and I use populate equals wildcard into the API endpoint, the response shows the page author user data.

`"createdBy": {
"id": 1,
"firstname": "User Firstname",
"lastname": "User Lastname",
"username": null,
"email": "User email",
"password": "encrypted password",
"resetPasswordToken": "encrypted token",
"registrationToken": null,
"isActive": true,
"blocked": false,
"preferedLanguage": null,
"createdAt": "2022-09-12T14:00:09.156Z",
"updatedAt": "2022-10-10T09:17:57.804Z"
},
"updatedBy": {
"id": 1,
"firstname": "User Firstname",
"lastname": "User Lastname",
"username": null,
"email": "User email",
"password": "encrypted password",
"resetPasswordToken": "encrypted token",
"registrationToken": null,
"isActive": true,
"blocked": false,
"preferedLanguage": null,
"createdAt": "2022-09-12T14:00:09.156Z",
"updatedAt": "2022-10-10T09:17:57.804Z"
},`

**Comment by cyp3rius** [comment]
Checking

**Comment by cyp3rius** [comment]
Fixed in `v2.3.2`
