### ISSUE TITLE
"Error: Entity not found" if renderNavigation navigationIdOrSlug calls a non-existant menu

### ISSUE THREAD

**Issue by amityweb** [VirtusLab-Open-Source/strapi-plugin-navigation#411]
If I have the following query, and "menuSlug" refers to a menu that does not exist, there is a server error and I do not know how to deal with it so our app just crashes. We are passing menuSlug from a text entry field in our Strapi, so a user could enter the wrong slig by mistake, one that does not exist, and then the app crashes due to the server error. 

How can your plugin return a null or something so we can deal with the error and not have a server error? 

For info, our app allows users to enter custom menus they create on any page. So we use a text field to enter the navigation slug because I do not know how to add a dropdown in Strapi that would list all the custom menus we create so a user could choose a menu from a list and avoid this issue, so instead they enter it into a text field. 

```
export async function fetchMenu(menuSlug) {

	const menu = await request(
		process.env.STRAPI_GRAPHQL,
		gql`
		query
		{
			data: renderNavigation(
				navigationIdOrSlug: "${menuSlug}"
				type: TREE
				menuOnly: false
			)
			{
				id
			}
		}`
	)
}
```

Error is the following. I have entered a menuSlug above of "this-menu-does-not-exist":

`Error: Entity not found: {"response":{"errors":[{"message":"Entity not found","extensions":{"error":{"name":"NotFoundError","message":"Entity not found","details":{}},"code":"STRAPI_NOT_FOUND_ERROR"}}],"data":null,"status":200,"headers":{}},"request":{"query":"\n\t\tquery\n\t\t{\n\t\t\tdata: renderNavigation(\n\t\t\t\tnavigationIdOrSlug: \"this-menu-does-not-exist\"\n\t\t\t\ttype: TREE\n\t\t\t\tmenuOnly: false\n\t\t\t)\n\t\t\t{\n\t\t\t\tid\n\t\t\t}\n\t\t}"}}`

**Comment by CodeVoyager** [comment]
Hi @amityweb 

I checked your query. We are inline with GraphQL standards. `Not Found` error is thrown as it is done for REST. Since it is client issue not server one I'm closing this query.

See more: https://learning.postman.com/open-technologies/blog/graphql-error-handling/

**Comment by amityweb** [comment]
Ahhh, right OK, I need to deal with the errors. Sorry to bother you. I must admit I am not very good at handing such errors, I normally just fix whatever the errors are which I could not do in this case. Other queries I have to Strapi do not return an error when something is not found, they return empty data arrays, so my error checking has been basically whether the returned data array has data or not! I had forgotten about handing errors I often don't use it. I think I will from now on. 

So I have managed to suppress the error with this:

```
export async function fetchMenu(menuSlug) {
	try {
		const menu = await request(
			process.env.STRAPI_GRAPHQL,
			gql`
			query
			{
				data: renderNavigation(
					navigationIdOrSlug: "${menuSlug}"
					type: TREE
					menuOnly: false
				)
				{
					id
				}
			}`
		)
		return menu;
	}
	catch (error)
	{
		console.log('Error Fetching Menu');
	}
}
```
