### ISSUE TITLE
Creating navigations that start with the same string causes issues

### ISSUE THREAD

**Issue by vladimir-djokic-quantox** [VirtusLab-Open-Source/strapi-plugin-navigation#418]
I'm not sure how to descibe this, but if I try to create two menu navigations

- `menu`
- `menu-mobile`

I end up with mixed up navigations:

<img width="851" alt="Screenshot 2024-03-08 at 16 14 03" src="https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/92777255/2e2219d8-c4f6-4bd6-8cc8-68382d1633b5">

Trying to delete the first one, deletes both with an error that I cannot take the screenshot of, as it disappears as soon as I try to capture it.

Strapi v4.17.1
Navigation v2.3.2

**Comment by cyp3rius** [comment]
Released as part of `v2.5.0`.

Note that was last major release containing features for **Strapi v4**.

**Comment by cyp3rius** [comment]
Closing.
