### ISSUE TITLE
Deleting a menu causes a global delete for all menu items in all other menus

### ISSUE THREAD

**Issue by Bryelmo** [VirtusLab-Open-Source/strapi-plugin-navigation#424]
Hi everyone,

I'm using:
Strapi v4.21.0
Navigation v2.4.0
Node v18.19.1
NPN v10.2.4

I deleted an useless menu (on my project) from the "Manage All Navigations" pop-up dialog and after that I noticed the all items in all other menus have been deleted, all plugin database tables are empty.

I tested a couple of time and the issue persist.

Thanks.

**Comment by eliasleyton** [comment]
Confirm.

**Comment by cyp3rius** [comment]
Released as part of `v2.5.0`.

Note that was last major release containing features for **Strapi v4**.
