### ISSUE TITLE
Internationalization not working

### ISSUE THREAD

**Issue by digi4care** [VirtusLab-Open-Source/strapi-plugin-navigation#426]
```
// plugin.js
module.exports = ({ env }) => ({
  navigation: {
    enabled: true,
  },
});

// package.json
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.1.1",
    "@creazy231/strapi-plugin-apollo-sandbox": "^0.0.13",
    "@strapi/plugin-graphql": "^4.23.1",
    "@strapi/plugin-i18n": "4.23.1",
    "@strapi/plugin-seo": "^1.9.8",
    "@strapi/plugin-users-permissions": "4.23.1",
    "@strapi/provider-upload-local": "^4.23.1",
    "@strapi/strapi": "4.23.1",
    "mysql": "2.18.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^5.2.0",
    "strapi-plugin-generate-data": "^1.0.32",
    "strapi-plugin-navigation": "^2.4.0",
    "strapi-plugin-placeholder": "^4.4.0",
    "strapi-plugin-responsive-image": "^1.2.0",
    "strapi-plugin-sitemap": "^3.1.1",
    "styled-components": "^5.2.1"
  },

// enviroment
│ Environment  │ development                           
│ Version            │ 4.23.1 (node v18.17.0)                 
│ Edition             │ Community                     
│ Database        │ mariadb

```
I enabled Internationalization in the /admin/settings/navigation settings.

However, when I navigate to this URL: http://localhost:1337/admin/plugins/navigation, I encounter an error and nothing is displayed. Upon further investigation, I discovered the source of the problem. In the database, the navigation table is created and a record named "Main Navigation" exists, but the locale field is not being populated, which is why I'm seeing an error and no content is displayed. If I manually insert a locale, such as 'en', into the database, then everything functions correctly. When I click on the "Manage" button, a modal titled "All navigations" appears, where I can edit the navigations, but there is no field available to set or edit the locale.

Essentially, I'm facing two issues: initially, the first navigation record is not set with the current default locale, and there is no possibility to change or set the locale afterward.

**Comment by cyp3rius** [comment]
Hello @digi4care,

check please recent release `v2.5.0`

**Comment by cyp3rius** [comment]
Closing.
