### ISSUE TITLE
Persistent "Read Fields from Related" Setting

### ISSUE THREAD

**Issue by medchedli** [VirtusLab-Open-Source/strapi-plugin-navigation#427]
I attempt to disable the "Read Fields from Related" option within navigation item settings. After saving the changes, I reopen the navigation item setting. I unexpectedly find the "Read Fields from Related" option enabled again (Always set to True).

```
$ node --version
v18.19.0

$ yarn strapi version
yarn run v1.22.19
$ strapi version
4.20.0
Done in 0.91s.

$ yarn list strapi-plugin-navigation
yarn list v1.22.19
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ strapi-plugin-navigation@2.4.0
Done in 0.38s.
```

**Comment by medchedli** [comment]
I upgraded to the latest release `strapi-plugin-navigation@2.5.0` and retested the issue, I still observe the same behaviour.

**Comment by eliasleyton** [comment]
Confirm in #432

**Comment by CodeVoyager** [comment]
This issues is addressed by related pull request. Have a look, please.
