### ISSUE TITLE
[BUG?] Audience collection does exist even when the field is disabled

### ISSUE THREAD

**Issue by SalahAdDin** [VirtusLab-Open-Source/strapi-plugin-navigation#429]
Honestly, we have to say, we don't understand what is that collection for so, so maybe it would not be an issue, but:
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/5034215/fd0d4f2e-0d9e-4564-956a-9dffc839302f)
And:
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/5034215/c96e2e80-ed4b-49a3-90bd-93eaca06189a)

Could you update the documentation explaining what and why audience?

Thank you!

Launched In: 1668 ms
Environment: development
OS: linux-x64
Strapi Version: 4.24.1
Node/Yarn Version: yarn/4.1.1 npm/? node/v20.12.2 linux x64
Edition: Community
Database: sqlite

**Comment by vincentgTroopers** [comment]
same issue here, not sure what this audience collection is about 

thanks for the work on this plugin !

**Comment by cyp3rius** [comment]
The Audience collection is built in Navigation Plugin collection to "filter" the navigations depend on the role / target audience of your client application. Collection is visible in Content Manager as it should. The Enable button is just to show and execute logic in the Nav Item form.

Closing the issue, as not an issue - hope I made it clear above :)

**Comment by cyp3rius** [comment]
You could, not should :) it's an option to use. For example we had a project where there were signed users with roles from external source on the client app, and we differ the items based on their roles.

We will add that to doc for v5

**Comment by lotarbo** [comment]
Sorry, but its possible to hide Audience collection?

**Comment by cyp3rius** [comment]
@lotarbo to do that you need to use Strapi Extensions approach and change the property in the schema to hide it.

**Comment by SalahAdDin** [comment]
@cyp3rius 

Well, version 5:

![Image](https://github.com/user-attachments/assets/2d30ebe0-b3f2-477d-8a52-909d4ba7544e)
I didn't add an Audience to the `additionalFields`, and it does not appear in the configuration panel.

![Image](https://github.com/user-attachments/assets/9c453353-5725-4e69-8444-755f3a2b712b)
The content-type is created!

Why?

**Comment by SalahAdDin** [comment]
> Sorry, but its possible to hide Audience collection?

Did you hide it?

**Comment by cyp3rius** [comment]
We didn't, this content type was always part of the plugin. The way to hide it is to use Strapi Extensions and amend the display settings of the Audience content type:

```json  
{
//...
pluginOptions: {
    "content-manager": {
      visible: false,
    },
    "content-type-builder": {
      visible: false,
    },
  },
//...
}
```

**Comment by SalahAdDin** [comment]
> We didn't, this content type was always part of the plugin. The way to hide it is to use Strapi Extensions and amend the display settings of the Audience content type:
> 
> {
> //...
> pluginOptions: {
>     "content-manager": {
>       visible: false,
>     },
>     "content-type-builder": {
>       visible: false,
>     },
>   },
> //...
> }

I didn't know that.

**Comment by SalahAdDin** [comment]
@cyp3rius 
But, even when the collection does exist, why isn't it in the Navigation configuration panel's custom fields?

![Image](https://github.com/user-attachments/assets/73178aa7-eb0f-4b6d-83d8-d4a267fb43ee)

**Comment by creadot** [comment]
> We didn't, this content type was always part of the plugin. The way to hide it is to use Strapi Extensions and amend the display settings of the Audience content type:
> 
> {
> //...
> pluginOptions: {
>     "content-manager": {
>       visible: false,
>     },
>     "content-type-builder": {
>       visible: false,
>     },
>   },
> //...
> }

For those who don't know where to put it: `/src/extensions/navigation/content-types/audience/schema.json` 🚀
