### ISSUE TITLE
Installing strapi-plugin-navigation breaks strapi entityService typescript

### ISSUE THREAD

**Issue by MarijnFK** [VirtusLab-Open-Source/strapi-plugin-navigation#431]
We've had problems with the entityService.update() not working correctly with typescript. See **https://github.com/strapi/strapi/issues/19252#issuecomment-2024738121** for more details

After diving into it and removing plugins one-by-one, we found that this plugin breaks the functionality

**Comment by cyp3rius** [comment]
We suggest to use `2.5.0` which is aligned with more recent Strapi package version.

**Comment by MarijnFK** [comment]
Using latest versions of strapi and plugin the problem persists
NodeJS version: v20.12.0

Packages:
```
"@strapi/plugin-i18n": "4.24.3",
"@strapi/plugin-users-permissions": "4.24.3",
"@strapi/provider-upload-cloudinary": "4.24.3",
"@strapi/strapi": "4.24.3",
"strapi-plugin-navigation": "2.5.0",
```

**Comment by cyp3rius** [comment]
@MarijnFK as per https://github.com/strapi/strapi/issues/19252#issuecomment-2132835139 it's a Strapi bug. Closing then.

**Comment by cyp3rius** [comment]
@MarijnFK `2.5.1` release with updated Strapi dependencies to `4.24.4`
