### ISSUE TITLE
[Bug] Save "Read fields from related" doesn't work

### ISSUE THREAD

**Issue by eliasleyton** [VirtusLab-Open-Source/strapi-plugin-navigation#432]
Prop "Read fields from related" not saving

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/3248095/27377ad8-c3e9-45aa-a163-5d0bd2b23784

**Comment by CodeVoyager** [comment]
This issues is addressed by related pull request. Have a look, please.

**Comment by cyp3rius** [comment]
Released in `2.5.2`
