### ISSUE TITLE
Strapi V5 support

### ISSUE THREAD

**Issue by michsko544** [VirtusLab-Open-Source/strapi-plugin-navigation#439]
Are there any plans to support Strapi version 5? I have tried to install a plugin on `strapi@5.0.0-rc.8` but I'm getting the following error while building the app:
```
Error: [commonjs--resolver] Missing "./EmptyDocuments" specifier in        ││   "@strapi/icons" package
```

**Comment by cyp3rius** [comment]
Hello @michsko544 , we're almost done with the migration for v5. Testing phase is in progress. Expect first beta in 1-2 weeks.

**Comment by cyp3rius** [comment]
the `3.0.0-beta.0` is live 🚀
