### ISSUE TITLE
EntityService typescript broken again

### ISSUE THREAD

**Issue by MarijnFK** [VirtusLab-Open-Source/strapi-plugin-navigation#441]
We're getting the same problem as before with the entityService after updating to latest strapi (in this case 4.25.8)
https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/431

Uninstalling strapi-plugin-navigation fixes the issue again

**Comment by cyp3rius** [comment]
We're going to update dependencies by today / tomorrow release.

**Comment by cyp3rius** [comment]
`v2.5.3` released with upgrades to newest `strapi@4.25.8` version.

**Comment by MarijnFK** [comment]
@cyp3rius i see the work on strapi-v5, sofar the current beta(3) works fine.
Altho strapi v5 is released, i'm not upgrading to v5 in production environments. 
Unfortunately upgrading to the latest strapi v4 breaks the typescript hinting again. Are you planning on releasing updates to v2 supporting the latest v4 versions? 
Or is there a way i can update to the latest v4 without the typescript-support breaking?

**Comment by cyp3rius** [comment]
I will try to release another version with dependencies bump tomorrow or in Friday
