### ISSUE TITLE
[CU-8695xua8h] Strapi v5 / Plugin v3 Inconsistent theme

### ISSUE THREAD

**Issue by liqueflies** [VirtusLab-Open-Source/strapi-plugin-navigation#446]
Hello, 

The plugin theme seems breaking on the heading part when changing system theme from "light" to "dark".
I attach a video for the reproduction

https://github.com/user-attachments/assets/a9cfdf12-b736-46d0-b245-48c627bc4fdd

**Comment by cyp3rius** [comment]
Noted and in progress already @liqueflies.

**Comment by cyp3rius** [comment]
Issue solved, we are going to release it in the upcoming `beta.1`

**Comment by cyp3rius** [comment]
Version `3.0.0-beta.1` released.
