### ISSUE TITLE
Strapi V5: Entities of Content-Types not shown when trying to create Navigation Item

### ISSUE THREAD

**Issue by albertshrpv** [VirtusLab-Open-Source/strapi-plugin-navigation#449]
When selecting a Content-Type when trying to create a new Navigation Item, no entities of the selected Content-Type are shown as seen in the screenshots below. There is a least one published entry of api::page.page, but it is not being found by the navigation plugin. Also tried with other Content-Types, same issue persists. Am I missing some extra configuration that was added with Strapi V5?

@strapi/strapi: 5.0.0
strapi-plugin-navigation: 3.0.0-beta.0

![image](https://github.com/user-attachments/assets/fb76edac-ef51-4e92-a04f-0eae4293de54)

![image](https://github.com/user-attachments/assets/6063e13f-6ada-4b5d-b59a-04c42c4cb97e)

**Comment by cyp3rius** [comment]
Thanks for reporting. Investigating.

**Comment by cyp3rius** [comment]
Linking task #8695y1kua

**Comment by cyp3rius** [comment]
The issue was fixed in the released version `3.0.0-beta.1`.
