### ISSUE TITLE
Strapi v5: GraphQL breaking change

### ISSUE THREAD

**Issue by liqueflies** [VirtusLab-Open-Source/strapi-plugin-navigation#450]
Hello,

I was trying to make a GraphQL query in order to get the Navigation UI, following the previous version, and documented also on the newest one the query should look like the following example:

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/tree/v5?tab=readme-ov-file#graphql-api

Looking at my /graphql endpoint It looks like it's changed and it's also weird:

<img width="1067" alt="Screenshot 2024-09-25 alle 15 28 19" src="https://github.com/user-attachments/assets/132fb6ce-852d-4393-b798-a7f84f0bbee7">

<img width="666" alt="Screenshot 2024-09-25 alle 15 44 02" src="https://github.com/user-attachments/assets/39e9ab2c-a9bc-458c-8cb2-b9dee06a16e1">

Is this correct?

Thank you,
Lorenzo

**Comment by cyp3rius** [comment]
@liqueflies we're adding support for `documentId` both for REST and GQL in next beta version. As for now use standard way with Ids.

**Comment by liqueflies** [comment]
Just for instance, i have to query the navigationNavigation document right?

**Comment by cyp3rius** [comment]
Those queries are generated by Strapi for all the content types, we supported and are going to support only our custom ones detailed here: https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/tree/v5?tab=readme-ov-file#graphql-api

**Comment by liqueflies** [comment]
> Those queries are generated by Strapi for all the content types.
> 
> We supported and are going to support only our custom ones detailed here: https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/tree/v5?tab=readme-ov-file#graphql-api
> 
> Also seems you didn't applied "the trick" with GQL initialization so built-in queries are registered instead of the plugin dedicated.
> 
> ```ts
> //config/plugins.ts
>    navigation: {
>     enabled: true,
>    },
>    graphql: {
>     enabled: true,
>    },
> ```

This worked it out!
Didn't noticed it at the end of the doc. 

Now queries are working as expected on the docs.
If you want to keep it open to support documentId, if not feel free to close

**Comment by cyp3rius** [comment]
Yeah, let's keep it - I'm on it already :)

**Comment by cyp3rius** [comment]
The issue was fixed in the released version `3.0.0-beta.1`.
