### ISSUE TITLE
Strapi v5: Cannot apply any value to Custom Field

### ISSUE THREAD

**Issue by pjaydev** [VirtusLab-Open-Source/strapi-plugin-navigation#455]
*Strapi: v5.0.1
strapi-plugin-navigation: 3.0.0-beta.0*

The UI does not allow to set any value for a custom field. I tried with all four field types.

It seems, the value of a custom field is set fixed to its field name. You can clearly see that on string-typed fields and on the render output (which for a field `MyField` always has the value:  `{..., "MyField": "MyField", ...}`.

In addition, the UI shows the *name* as label of the custom field instead of showing the defined *label*.

**Comment by cyp3rius** [comment]
The issue was fixed in the released version `3.0.0-beta.1`.
