### ISSUE TITLE
Strapi v5: Incorrect UI order of menu with nested items

### ISSUE THREAD

**Issue by michsko544** [VirtusLab-Open-Source/strapi-plugin-navigation#459]
Version: `3.0.0-beta.2`
Strapi: `5.0.5`

I found a bug that caused incorrect ordering of navigation items (with nested items). The response from GraphQL API returns the correct order. Expected: Same order both returned from API and in UI

Steps to reproduce:
- create navigation with at least 2 items
- add nested items to 1 element
- set navigation with nested items to be the last
- click the 'save' button
- the order will break

Additionally, when I reorder a broken list, the order will be fixed until I save it again

![Zrzut ekranu 2024-10-17 o 14 28 12](https://github.com/user-attachments/assets/7824ed8b-261f-4385-8a22-36a838d211da)
![Zrzut ekranu 2024-10-17 o 14 31 22](https://github.com/user-attachments/assets/12cb8e59-0163-43a5-a2ad-af5b1200aa19)

**Comment by cyp3rius** [comment]
Thanks for reporting @michsko544 I'm working on fixing the i18n so will take care of it as well. Should be done during upcoming weekend.

**Comment by cyp3rius** [comment]
Issue was fixed in `v3.0.0-beta.3`
