### ISSUE TITLE
Strapi v5: Broken "Restart Strapi" flow

### ISSUE THREAD

**Issue by michsko544** [VirtusLab-Open-Source/strapi-plugin-navigation#462]
Version: `3.0.0-beta.2`
Strapi: `5.0.5`

When I apply changes to the plugin config and click "Restart Strapi," many errors appear. After that, I am redirected to the register page.

It would be nice to see flow like when I update the Strapi schema in the admin panel. The server is restarting and the page just refreshes.

![Zrzut ekranu 2024-10-17 o 16 04 43](https://github.com/user-attachments/assets/99e8c0c8-a749-4545-8e15-887af449a833)
![Zrzut ekranu 2024-10-17 o 16 04 50](https://github.com/user-attachments/assets/299342dd-48dc-4791-ac15-66fa39154015)
![Zrzut ekranu 2024-10-17 o 16 05 24](https://github.com/user-attachments/assets/ea827c73-1c6c-41ee-952d-1cb252145706)

**Comment by cyp3rius** [comment]
Fixed in `3.0.0-beta.7`
