### ISSUE TITLE
Strapi v4: Media field missing label

### ISSUE THREAD

**Issue by dchntsv** [VirtusLab-Open-Source/strapi-plugin-navigation#467]
Hello!

I am using strapi v4.25.11 and strapi-plugin-navigation v2.5.4. I added multiple additional fields through config/plugins, including two media fields, eg. 
`{
  enabled: true,
  label: 'Main image',
  multi: false,
  name: 'mainImage',
  options: [],
  required: false,
  type: 'media',
},`.

The added fields are visible in the add/edit navigation item popup as it is shown in the screenshot, but the labels of the fields are missing. Although, it is not shown in the screenshot, the labels for other types of additional fields (select, string or number) are visible.

Is this a bug? I was very happy seeing that the media type was introduced for the additional fields, but this issue do not allow me to make use of it. Could you take a look of this?

![Screenshot from 2024-10-30 10-17-17](https://github.com/user-attachments/assets/4cb10d12-6f8b-4b89-8039-f970bd75022b)

**Comment by cyp3rius** [comment]
Fixed in `v2.5.6`
