### ISSUE TITLE
Strapi v5: Unable to set custom boolean field value to false

### ISSUE THREAD

**Issue by pjaydev** [VirtusLab-Open-Source/strapi-plugin-navigation#468]
Version: `3.0.0-beta.4`
Strapi: `5.2.0`

I am unable to set the value of any custom boolean field to `false`. 

On re-opening the Navigation Item Editor, the value always skips back to `true` and the API also always returns `true`.

Thanks!

**Comment by cyp3rius** [comment]
Fixed in `v3.0.0-beta.5`. Note that Strapi dependency was also bumped to `v5.3.0`

**Comment by pjaydev** [comment]
Great, thanks!
