### ISSUE TITLE
Error Report: "popup.item.form.uiRouter.unableToRender" When Creating New Menu Item

### ISSUE THREAD

**Issue by holmanlam** [VirtusLab-Open-Source/strapi-plugin-navigation#478]
I encountered the following error when trying to create a new menu item:
popup.item.form.uiRouter.unableToRender

Details
I suspect this error is due to the slugify function not supporting languages other than English. Specifically, the creation of the menu item fails when using non-English characters.

<img width="847" alt="Screenshot 2024-12-21 at 10 59 13 AM" src="https://github.com/user-attachments/assets/e275519d-2e13-4156-8b70-69c39966a09e" />

Expected Behavior
I would like to successfully create menu items with non-English characters, or receive a clear error message when unsupported characters are used.

**Comment by cyp3rius** [comment]
@holmanlam May we ask for the details like:
- Strapi version
- Plugin version
- Console logs (server and browser)

Did you implemented the custom sług parser function to handle non-english chars in slugs?

**Comment by holmanlam** [comment]
Strapi version: 5.6.0
Plugin version: 3.0.0
Console logs (server and browser)

There are no logs in the console, but I see that http://localhost:1337/navigation/slug?q=%E6%B8%AC%E8%A9%A6 returns an empty result. Therefore, I suspect it's an issue with Chinese. I also found the documentation for @sindresorhus/slugify, which states that Chinese is not supported.
<img width="727" alt="Screenshot 2024-12-22 at 12 17 25 PM" src="https://github.com/user-attachments/assets/c195db17-ae84-4b95-9a61-a12c49af89a8" />

Is there a way to manually input the slug?

**Comment by cyp3rius** [comment]
There are two ways to get what you expect:

1. Add the described function extension for slugify to parse the non-english chars - that's the designed and recommended approach if you would get it automaticaly generated
2. Create the slug field in the content type you are using and set this field as a slug source in settings. Although this won't cover **Wrapper** element slug generation.

Both strategies could be mixed together to get the expected and working outcome.

**Comment by holmanlam** [comment]
Thank you for your reply. However, does this mean I need to change the plugin myself? I'm not very familiar with how to modify plugins...

**Comment by cyp3rius** [comment]
The case is addressed since Strapi 4 by using the Strapi Exptensions interface where you can easly extend / modify plugin behavior. See the Readme:

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation?tab=readme-ov-file#slug-generation

Where the reference to official doc is provided as well.

**Comment by cyp3rius** [comment]
Closing hence guidance provided.

The missing translation is going to be fixed in between other planned work.
