### ISSUE TITLE
NPM package contains PNG images

### ISSUE THREAD

**Issue by jorrit** [VirtusLab-Open-Source/strapi-plugin-navigation#480]
The npm package is quite large. One of the causes is 2.7 MB of PNG images. Could they be removed?

If not, these images could be compressed using tinypng.com to reduce the file size by 74%.

I could make a PR for either solution, whatever you prefer.

**Comment by cyp3rius** [comment]
I would say they are not required. Let me amend the build process and `.npmignore`

**Comment by cyp3rius** [comment]
Fixed in `3.0.1`
