### ISSUE TITLE
GraphQL API still uses attributes for related item fields

### ISSUE THREAD

**Issue by jorrit** [VirtusLab-Open-Source/strapi-plugin-navigation#485]
In Strapi 5 the `attributes` property was removed, so fields of entities are added directly to the entity object. See https://docs.strapi.io/dev-docs/migration/v4-to-v5/breaking-changes/new-response-format.

The GraphQL response format still exposes an `attributes` field with the related item data:

```graphql
type NavigationItemRelatedData {
    attributes: NavigationItemRelated
    documentId: String!
    id: Int
}

union NavigationItemRelated = PageType1 | PageType2
```

The `attributes` field is always empty in the GraphQL response. I think the GraphQL schema needs to be changed to make `NavigationItemRelatedData` the union.

**Comment by cyp3rius** [comment]
Fixed in `v3.0.3`
