### ISSUE TITLE
Unable to change Navigation Item Type when no Collection is enabled for the plugin

### ISSUE THREAD

**Issue by CodeToTee** [VirtusLab-Open-Source/strapi-plugin-navigation#490]
Perhaps I'm trying to use the plugin incorrectly.  I'm trying to create a navigation menu without using any of my collections.  Specifically, when I try to create a new menu item, the save button is never enabled.

For my case, I'm simply trying to use the plugin to allow my admin to create the menu structure, using URLs for each menu item.  When I add a new item, the save button is never enabled.

Additionally, I've added two custom fields to the menu items, but they don't appear in the New Item entry screen.

Am I using the plugin improperly?  Thanks in advance for your feedback.

https://github.com/user-attachments/assets/b0644af2-cbf2-4374-a32e-c72d51825da8

PS: Thanks of the quick-fix for #487

**Comment by cyp3rius** [comment]
I see a potential gap in the logic here. 

We assumed based on the most of use cases that at least one Collection / Single Type is going to be enabled and the `Navigation item type` checks if it is true or not. What I can ask you as an interim "fix" is to enable at least one collection in settings and you'll get this dropdown enabled for selection between "Internal source", "External source", "Wrapper".

We'll fix that check soon, as part of the next release.

**Comment by CodeToTee** [comment]
Thank you !  That's very helpful.  I simply added an arbitrary collection (and didn't fill-in any of the supporting fields), then attached a menu item to an arbitrary collection entry.  That allowed me to save, and I can see the menu in the API.  Thanks for the fast response!  Much appreciated!

**Comment by CodeToTee** [comment]
Any comments on the second part of the issue?  I've added a couple 'Additional Fields (in my case, they're called `blurb` which is a string, and `icon`, which is media).  I expected those input fields to appear in the UI when creating a new Menu Item.  I don't see the input fields, nor do I see the fields in the API response when trying to `render` the API.

Am I doing something wrong?

**Comment by cyp3rius** [comment]
Might be connected with the same check and/or with selected Internal Type. 

Need to investigate it, then can provide more info. Hopefully tomorrow.

**Comment by cyp3rius** [comment]
@CodeToTee in regard to the additional fields seems you've got them set as `not visible`. By default and to avoid unexpected behaviors of already existing navigation items when you're adding a new additional field is set to hidden. Use the `eye` button to change the visibility and save the changes.

**Comment by cyp3rius** [comment]
Fixed in `v3.0.3`

**Comment by CodeToTee** [comment]
Thanks, @cyp3rius !  Sorry I missed the 'hidden' flag.  Your quick response is much appreciated!

**Comment by cyp3rius** [comment]
No probs, the newest version has reordered buttons so it should help a bit.
