### ISSUE TITLE
Unable to use the same entities in different navigations

### ISSUE THREAD

**Issue by JelmerV-WFC** [VirtusLab-Open-Source/strapi-plugin-navigation#50]
When using the same entities in different navigations the entity relation of the existing navigation item is removed.

First navigation item:
![image](https://user-images.githubusercontent.com/39594925/111328296-67be9580-866e-11eb-8d2e-1c7b169cf490.png)

Second navigation item:
![image](https://user-images.githubusercontent.com/39594925/111328196-51b0d500-866e-11eb-8489-a2bbaa5dcd3a.png)

Is there something I'm doing wrong?

**Comment by cyp3rius** [comment]
Hi @JelmerV-WFC,

That's the case of polymorphic relations, it's overriding the relation like page - item. Those multiple navs we're not supporting from the level of UI yet. That's planned for 1.1 version.

**Comment by JelmerV-WFC** [comment]
Hi @cyp3rius!
Alright! Do you know if there is a workaround for the time being?

**Comment by cyp3rius** [comment]
The question if you really want to differ the navigations for footer and header :) What I can guide you is to create the Auditory keys like `header`, `footer` and add relevant ones to the each item of your navigation. Than on the client app or the backend part of it you might filter out the items you're not interested in. 

That's not a perfect solution, but a workaround that has helped couple of people already.

**Comment by welch08** [comment]
@JelmerV-WFC Hello! How did you create two navigation? I don't see any select fields

**Comment by rodsotdia** [comment]
I had the same question as @welch08 How can we create more than one navigation? I can't find any related on the docs. Any guide about this? Thanks.

**Comment by cyp3rius** [comment]
@shyr1punk planned release for Friday 22nd Oct, last tests are conducted.

**Comment by km185273** [comment]
Any updates on the planned release of this feature? I am waiting on this and i18n Navigation before I can use this plugin.

**Comment by cyp3rius** [comment]
We've released version `1.1.0` where polymorphic relations has been removed and provided support for multiple navigations (enabled it in native Content Manager).
