### ISSUE TITLE
GraphQL request

### ISSUE THREAD

**Issue by zvekov** [VirtusLab-Open-Source/strapi-plugin-navigation#54]
Hello!
This plugin support GraphQL requests?

for example 
```
query {
  navigation(id: "1") {
    render {
      id
      title
      path
      slug
    }
  }
}
```

**Comment by cyp3rius** [comment]
Hi @zvekov,

Not yet. We've got it in the backlog.

**Comment by cyp3rius** [comment]
To be developed:

1. Native support for GQL in Strapi
2. Research topic with Gatsby (https://www.gatsbyjs.com/plugins/gatsby-source-strapi-plugin-navigation/?=strapi)

**Comment by cyp3rius** [comment]
Version `v1.0.4` which contains requested feature has been released.
