### ISSUE TITLE
Collection type same name

### ISSUE THREAD

**Issue by kuldeeparora** [VirtusLab-Open-Source/strapi-plugin-navigation#55]
Throwing error if we already got a collection-type with the same name "navigation"

here is the error code
```
debug ⛔️ Server wasn't able to start properly.
error Error: Duplicated collection name: `navigations`.
The same collection name can't be used for two different models.
First found in API `navigation`, model `navigation`.
Second found in Plugin `navigation`, model `navigation`.

```

**Comment by cyp3rius** [comment]
@kuldeeparora we will consider changing the content type identificators to more plugin related. That should avoid conflicts.

**Comment by cyp3rius** [comment]
Won't do for v3, Strapi v4 solves this internally.
