### ISSUE TITLE
how to create a navigation like this

### ISSUE THREAD

**Issue by Tiramisupxl** [VirtusLab-Open-Source/strapi-plugin-navigation#58]
Hello, I would like to create a navigation like this: 
![image](https://user-images.githubusercontent.com/13674347/116497890-fb74ba00-a8da-11eb-99f2-d4f0bb67d271.png)
I just want to link the content or url in dropdown menu, not all navigation item.But the plugin require me to fill the two fields, url and relation to content type.How can I modify them? Thanks so much
![image](https://user-images.githubusercontent.com/13674347/116497986-3d9dfb80-a8db-11eb-9278-930d8e02de70.png)

**Comment by cyp3rius** [comment]
Hi @Tiramisupxl, 

we've taken an assumption that navigation is going to be build based on the existing content types, so each item will contain relation to the content type (and might be nested down) or external link. You've to think about building it more like a site structure.

In your case you've to create a content type that will be related with "Navigation Three - Submenu" item and then add couple of a child elements to it. If you want to group them by some attribute, you can use also the Audience content type. Up to you how you're going to manage it in the client app.

Hope I've explained it a bit.

**Comment by Tiramisupxl** [comment]
> Hi @Tiramisupxl,
> 
> we've taken an assumption that navigation is going to be build based on the existing content types, so each item will contain relation to the content type (and might be nested down) or external link. You've to think about building it more like a site structure.
> 
> In your case you've to create a content type that will be related with "Navigation Three - Submenu" item and then add couple of a child elements to it. If you want to group them by some attribute, you can use also the Audience content type. Up to you how you're going to manage it in the client app.
> 
> Hope I've explained it a bit.

Thank you for your replay. Your answer tells me a lot about the plugin and strapi.  I have found the solution from a youtube video someone taught how to make the menu in strapi. Anyway, thanks a lot!
