### ISSUE TITLE
Can't leave title blank

### ISSUE THREAD

**Issue by ElGrimbo** [VirtusLab-Open-Source/strapi-plugin-navigation#61]
I'm new to Strapi and this plugin, so hope I haven't missed anything. But I'm following the install instructions [here](https://www.npmjs.com/package/strapi-plugin-navigation) and getting the error below when I leave the title field blank.

![image](https://user-images.githubusercontent.com/10922976/117678368-3b735100-b1a7-11eb-9421-d0ef728c150f.png)

My dependencies:
"knex": "0.21.18",
"sqlite3": "5.0.0",
"strapi": "3.6.1",
"strapi-admin": "3.6.1",
"strapi-connector-bookshelf": "3.6.1",
"strapi-plugin-content-manager": "3.6.1",
"strapi-plugin-content-type-builder": "3.6.1",
"strapi-plugin-email": "3.6.1",
"strapi-plugin-i18n": "3.6.1",
"strapi-plugin-navigation": "^1.0.1",
"strapi-plugin-upload": "3.6.1",
"strapi-plugin-users-permissions": "3.6.1",
"strapi-utils": "3.6.1"

Windows 10
Yarn 1.23.0-20210103.1434
NPM 6.14.11
Node.js 14.16.0

**Comment by cyp3rius** [comment]
Released as `v1.0.2`
