### ISSUE TITLE
Unable to view navigationItems

### ISSUE THREAD

**Issue by HijlcoL** [VirtusLab-Open-Source/strapi-plugin-navigation#62]
When trying to view navigation items I'm getting an TypeError: `Cannot read property 'pluginOptions' of undefined`.

Configuration settings:
Docker desktop 3.3.2
MacOS 11.2.3
node 12.20.1
Strapi 3.6.1
Strapi-plugin-navigation 1.0.1

I'm running strapi in a docker container with the --watch-admin flag.
![Screen Shot 2021-05-11 at 10 39 07 AM](https://user-images.githubusercontent.com/4363017/117787460-be97b400-b246-11eb-9d62-847020919043.png)
This is a screenshot of the error message in my console.

**Comment by cyp3rius** [comment]
Hi @HijlcoL, please use the delivered UI Navigation interface (Plugins section on the left sidebar). We're waiting for next Strapi version to hide the Content Manager entities as we're not supporting this interface because of customs.
