### ISSUE TITLE
No validation when updating without an entity relation, throws error

### ISSUE THREAD

**Issue by ElGrimbo** [VirtusLab-Open-Source/strapi-plugin-navigation#65]
Small bug:

When updating an item it appears there's no validation, as when I hit the Update Item button I get an error:

![image](https://user-images.githubusercontent.com/10922976/117995055-e9facb80-b338-11eb-9abf-0f56f2164278.png)

My dependencies:
"knex": "0.21.18",
"sqlite3": "5.0.0",
"strapi": "3.6.1",
"strapi-admin": "3.6.1",
"strapi-connector-bookshelf": "3.6.1",
"strapi-plugin-content-manager": "3.6.1",
"strapi-plugin-content-type-builder": "3.6.1",
"strapi-plugin-email": "3.6.1",
"strapi-plugin-i18n": "3.6.1",
"strapi-plugin-navigation": "^1.0.1",
"strapi-plugin-upload": "3.6.1",
"strapi-plugin-users-permissions": "3.6.1",
"strapi-utils": "3.6.1"

Windows 10
Yarn 1.23.0-20210103.1434
NPM 6.14.11
Node.js 14.16.0

**Comment by cyp3rius** [comment]
Released as `v1.0.2`
