### ISSUE TITLE
support navigation for content types created by plugins

### ISSUE THREAD

**Issue by simpian** [VirtusLab-Open-Source/strapi-plugin-navigation#68]
I have a plugin that creates a number of content types once installed, however when I add the following code to my model, 
```
    "navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
    }
```

I get errors on pluralization `error TypeError: Cannot read property 'toLowerCase' of undefined`

The problem is actually in services/navigation.js, line 131. 

`const endpoint = isSingle ? apiName : pluralize(apiName);` 

Code is trying to pluralize `apiName`, but my plugin didn't create any APIs, so apiName is `undefined` in this case and throws TypeError.

**Comment by simpian** [comment]
```
       const { uid, options, info, collectionName, modelName, apiName, plugin, kind } = item;
        const pluralizeName = apiName ? apiName : modelName;
```

use `modelName`  for plugins and apiName for manually added content types seems to fix this issue. Are we able to add this?

**Comment by cyp3rius** [comment]
Hi @simpian,

yep sounds easy to do. I’m working on couple other bug fixes and will include this one. Should be available in 2-3 days.
