### ISSUE TITLE
The issue with Content type Entity not showing title in dropdown

### ISSUE THREAD

**Issue by makulatura** [VirtusLab-Open-Source/strapi-plugin-navigation#78]
Hi,

Firstly, thank you for creating this plugin. I decided to write a bit more info on how to deal with setting up this plugin, since it took me quite a while to get to successful result and documentation seems to be written for experienced users (a whole customization file would help).
I wanted to allow Navigation to use Pages content type. That was easy, but next, there was an issue with content type entity not showing title. Documentation suggests that I have to put "snippet as part of config/custom.js". I did not have that file and could not find any reference anywhere on the web to it or what to put inside it, but I succeeded when I put provided snippet in config/custom.**json** so it looks like this:

{
   "plugins":{
      "navigation":{
         "additionalFields":[
            "audience"
         ],
         "excludedContentTypes":[
            "plugins::",
            "strapi"
         ],
         "allowedLevels":2,
         "contentTypesNameFields":{
            "pages":[
               "Title"
            ]
         }
      }
   }
}

I had to do this, since my content type Page had a title field with capital T instead of default lowercase one. Also, be aware of letter casing for content type - for me it was page with lowercase p.
When you open developer tools network tab while in Navigation admin panel, you can see config request where you can make sure that your config is actually taken in account and in contentTypes - what is the right casing for content type.

![image](https://user-images.githubusercontent.com/988791/120662744-0dc1b500-c492-11eb-8ac7-9687aae1c5da.png)

**Comment by cyp3rius** [comment]
@makulatura may I ask you for providing a Readme.md contribution? :)

**Comment by rodsotdia** [comment]
Thanks, @makulatura for this, I had doubts about that config as well, I couldn't find anything related to `custom.js` file.

**Comment by ILCAI** [comment]
Thank you @makulatura for contributing! I had a similar issue, as I posted another issue, @cyp3rius . My problem was a wrong typed collectionName (singular/plural). It is working. Thank you.

**Comment by cyp3rius** [comment]
No longer valid, we've changed the approach.
