### ISSUE TITLE
[CU-21mwpq0] Webhooks

### ISSUE THREAD

**Issue by WWAZ** [VirtusLab-Open-Source/strapi-plugin-navigation#79]
Hi folks,

thanks for this nice plugin. To use it in production, it would be important that webhooks would be sent with every change. Do you plan to support webhooks for the next version?

**Comment by cyp3rius** [comment]
Hi @WWAZ, good point to consider. We will look into it.

**Comment by everythinginjs** [comment]
Hello @cyp3rius  is there any news on web hooks for navigation UI ?

**Comment by whatcoteam** [comment]
Hey @cyp3rius, I have tried both beta versions and as a conclusion types like tree, flat, rfr do not work in those version.

**Comment by cyp3rius** [comment]
@whatcoteam there was a change for those enums because of GQL consistency. You must use `FLAT`, `TREE`, `RFR`

**Comment by cyp3rius** [comment]
Released as part of major version `2.1.0`
