### ISSUE TITLE
What is the purpose of the menuAttached / Attach to menu feature?

### ISSUE THREAD

**Issue by ILCAI** [VirtusLab-Open-Source/strapi-plugin-navigation#80]

**Comment by cyp3rius** [comment]
Hello @ILCAI ,

the purpose of it is to simple identify which items have to be rendered as menu and which are simply the information structure of the page.

This property is dedicated to use by API response consumers, like you client app for example. You dont need to use it, but you can if it provides some value for you.

**Comment by ILCAI** [comment]
I see. Thank you, @cyp3rius - I get the clue that this plugin's functionality is a nice approach for having a bridge between page-structure and menu-structure, that always has provoked the question about redundancy for me. Using this approach I think I will
- use pages / posts / infopages / ... as a flat pool of data without hierarchy, perhaps with a category system
- use then navigation plugin to set a hierarchy and a sitemap / slug map
- build menus in the frontend with the possibility to pull data from the navigation plugin and/or being completely custom
