### ISSUE TITLE
Unable to add new fields to content type with navigation attribute

### ISSUE THREAD

**Issue by rodsotdia** [VirtusLab-Open-Source/strapi-plugin-navigation#82]
I have a single content type called "Contacts", so I've added the attribute navigation into `contacts.settings.json` as follow:

```
"navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
    }
```

But, when I try to add a new field into this single content type and then try to save the changes, Strapi throws an error:

![image](https://user-images.githubusercontent.com/58403142/122126400-c7068e80-ce85-11eb-9dc7-09e99d659129.png)

In the console the error shows as follow:

![image](https://user-images.githubusercontent.com/58403142/122126433-d84f9b00-ce85-11eb-987e-2677f115ddff.png)

And in the terminal, while Strapi is running:

![image](https://user-images.githubusercontent.com/58403142/122126471-e6052080-ce85-11eb-9f2e-4a4f542d8fa1.png)

If I remove the attribute navigation from `contacts.settings.json`, I can add new fields and save the changes correctly.

These are my dependencies:
```
    "knex": "0.21.18",
    "sqlite3": "5.0.0",
    "strapi": "3.6.3",
    "strapi-admin": "3.6.3",
    "strapi-connector-bookshelf": "3.6.3",
    "strapi-plugin-content-manager": "3.6.3",
    "strapi-plugin-content-type-builder": "3.6.3",
    "strapi-plugin-email": "3.6.3",
    "strapi-plugin-i18n": "3.6.3",
    "strapi-plugin-navigation": "^1.0.2",
    "strapi-plugin-upload": "3.6.3",
    "strapi-plugin-users-permissions": "3.6.3",
    "strapi-utils": "3.6.3"
```

**Comment by cyp3rius** [comment]
Hi @rodsotdia ,

It's known as we're using advanced polymorphic relation which is not supported by Strapi Content Builder. Once you provide it via JSON schema, you've to make all the changes also by editing JSON. We're going to change is as part of #50 which is on the backlog already.

Ref #47
