### ISSUE TITLE
Cannot create internal navigation item (no relation to content type shown)

### ISSUE THREAD

**Issue by baermathias** [VirtusLab-Open-Source/strapi-plugin-navigation#87]
I would like to create a navigation item of the type `internal`. For this the field `relation to content type` is required, but it is empty even if I have created multiple entries inside all of my collections, see screenshot:

![Screenshot from 2021-07-22 07-33-16](https://user-images.githubusercontent.com/45003352/126594134-1816e419-0175-496f-8c0c-17a706197373.png)

**Comment by Kronos66** [comment]
Hi @baermathias 
Could you send your config content types? Without this information, we can't help because we don't know how you configured the content type and we can't check is it correct.

**Comment by calpa** [comment]
Same problem here, any ideas?

/api/homepage/models/homepage.settings.json

```json
{
  "kind": "singleType",
  "collectionName": "homepages",
  "info": {
    "name": "Homepage"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "seo": {
      "type": "component",
      "repeatable": false,
      "component": "shared.seo"
    },
    "hero": {
      "type": "component",
      "repeatable": false,
      "component": "sections.hero",
      "required": true
    },
    "navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
    }
  }
}

```

**Comment by forntoh** [comment]
I have the same problem

**Comment by Kronos66** [comment]
Hi, @calpa I checked your case, and what I can do if you have a single type then should be available. I didn't see it on the list when I didn't have it in the database, we check this on fetching config from the server. 
For other cases, I can't check/help without more information :(.
