### ISSUE TITLE
[CU-20rfk7h] i18n Navigation

### ISSUE THREAD

**Issue by cyp3rius** [VirtusLab-Open-Source/strapi-plugin-navigation#90]
1. Provide ability to:
  - edit navigation name
  - change navigation visibility
  - select available languages for navigation entity

2. All navigation options should be possible to edit via modal triggered by clicking `Settings` button on a right hand side of a screen.
3. Provide ability to set item title in all navigation languages.
4. Extend `render` and `renderType` method to consume language and return navigation with translated items (if possible)

based on discussion https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/discussions/60

**Comment by Kinbaum** [comment]
@cyp3rius Do you have an ETA on when this will get released?

**Comment by Kinbaum** [comment]
Fantastic!

**Comment by cyp3rius** [comment]
Released as `v2.1.0-beta.1`. Use and test with respect, it's beta ;)

**Comment by Kinbaum** [comment]
Good stuff! 

First thing I noticed is in the GraphQL query, the locale type is set to `String` when it should be set as `I18NLocaleCode`

**Comment by Kinbaum** [comment]
When using a wrapper element in the beta, it throws this error and my UI crashes

<img width="1392" alt="Screen Shot 2022-05-05 at 12 17 50 PM" src="https://user-images.githubusercontent.com/6590356/166967644-24d79c4d-e5e1-4312-af07-7d267cc3e5ee.png">

**Comment by CodeVoyager** [comment]
Hi @Kinbaum a PR to fix one of reported issues is created. Have a look, please.

**Comment by Kinbaum** [comment]
> Hi @Kinbaum a PR to fix one of reported issues is created. Have a look, please.

LGTM

**Comment by ltsNotMike** [comment]
@mmathys Can you provide more context? What steps are there to reproduce? Do you have i18n enabled? Is this on a fresh installation or on a project migrated from another version? I'm investigating this issue but could not reproduce this error.

**Comment by skyclb** [comment]
I think they are wrong named and should be opposite, because `2.1.0-beta.1` has more recent changes and looks more advanced than `2.1.0-beta.2`. Or am i wrong?

**Comment by cyp3rius** [comment]
Released as part of major version `2.1.0`
