### ISSUE TITLE
Typo (?) in strapi-plugin-navigation/services/navigation.js ; npm run build fails 

### ISSUE THREAD

**Issue by nickft** [VirtusLab-Open-Source/strapi-plugin-navigation#95]
When I tried to install the plugin on a strapi instance at the point where I had to run 

**npm run build**

the process exited with status 1 due to the following errors:

strapi-plugin-navigation/services/navigation.js:302 ( switch (type?.toLowerCase()) )
strapi-plugin-navigation/services/navigation.js:355 (  audience: item.audience?.map(_ => _.key)  )

After I erased the '?' from both entries, the installation completed successfully.

**Comment by cyp3rius** [comment]
@nickft that seems like an issue with ES version, the `?` operator has been introduced some time ago already. What version of Strapi and node you've got?

**Comment by nickft** [comment]
@cyp3rius yes you're right, sorry for that. Indeed my node version is v10.19.0 which is way lower than v14 where optional  chaining is introduced. Thank you for the fast response. Closing the issue.
