### ISSUE TITLE
Multiple Navigation Portal

### ISSUE THREAD

**Issue by TylerOlthuizen** [VirtusLab-Open-Source/strapi-plugin-navigation#98]
How can I have multiple Navigations? I notice in some older screenshots there is a select dropdown to select a different navigation menu.

Thanks!

**Comment by cyp3rius** [comment]
Hi @TylerOlthuizen,

you're indeed right :) We're doing to re-enable the Navigation collection after introducing #93 changes. That's because polymorphic relations does not support multiple linkings. Should be within 1 - 2 weeks.

**Comment by TylerOlthuizen** [comment]
Sounds good! Thank you

**Comment by anthonytison** [comment]
Hi @cyp3rius,
I can see that this issue is closed but i didn't find any tutorial for setting multiple navigations. Could you explain to me how to do it plz ?
Thx

**Comment by cyp3rius** [comment]
Hi @anthonytison , following the release notes we've enabled `Navigation` collection so it should be visible on the top menu section. You can add multiple navigations there.

**Comment by anthonytison** [comment]
Right!! I totally missed this one. 
Thx :)
