### ISSUE TITLE
Error after edit audience field

### ISSUE THREAD

**Issue by rieset** [VirtusLab-Open-Source/strapi-plugin-navigation#99]
strapi-plugin-navigation/services/navigation.js

In function **updateBranch**. Argument **toUpdate** look like:
```
{..., audience: [null]}
{..., audience: [null]}
{..., audience: [null]}
{..., audience: [null, 'id new value']}
```

Select **Audience** in popup edit navigation item, works with error. Values not correct after edit

```
(5) [{…}, {…}, {…}, {…}, {…}]
0: {_id: "6141c3a20db9857732d3a6af", name: "Footer / Use", key: "footer-use", …}
1: {_id: "6141c3af0db9857732d3a6b0", name: "Footer / Build", key: "footer-build", …}
2: {_id: "6141c9af7482d3784cce44b5", name: "Header", key: "header", …}
3: {value: undefined, label: "Footer / Socials"}
4: {value: "6141c9677482d3784cce44b4", label: "Footer / Documents"}
```

**Comment by Kronos66** [comment]
Hi @rieset 
Could you send to us your configuration, and add more description what exactly was wrong, for now, I don't have enough information to take this bug and help you

**Comment by rieset** [comment]
When I change the navigationItem (if it has an audience tag) I get an error in the admin panel

If it is the first time I create an Audience Tag, everything is saved

If I edit the navigationItem with the audience tag, I get the error

When editing (without changing the saved audience tag) the **updateBranch** function sends audience equal to **null**. This causes an error

- Latest clear Strapi
- Navigation plugin with enabled audience tags

**Comment by rieset** [comment]
React select in admin after edit navigationItem sends null to **updateBranch** function, instead of id audience tag
